name: domino
version: 0.1.0.0

dependencies:
  - base >= 4.7 && < 5
  - gloss
  - random
  - random-shuffle
  - mtl
  - vector
  - pretty

library:
  source-dirs: src
  dependencies:
    - gloss
    - random
    - random-shuffle
    - mtl
    - vector

executables:
  domino-exe:
    main: Main.hs
    source-dirs: app
    dependencies:
      - domino
      - gloss
      - random
      - random-shuffle
      - mtl
      - vector
      - pretty
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
