{-# LANGUAGE OverloadedStrings #-}

module Web.Views 
    ( indexHtml
    , gameHtml
    ) where

import Data.Text.Lazy (Text)
import qualified Data.Text.Lazy as TL

-- | Página principal
indexHtml :: Text
indexHtml = TL.concat
    [ "<!DOCTYPE html>"
    , "<html lang='es'>"
    , "<head>"
    , "  <meta charset='UTF-8'>"
    , "  <meta name='viewport' content='width=device-width, initial-scale=1.0'>"
    , "  <title>Dominó - Haskell</title>"
    , "  <style>", cssStyles, indexCssStyles, "</style>"
    , "</head>"
    , "<body>"
    , "  <div class='container' id='main-menu'>"
    , "    <div class='title-container'>"
    , "      <div class='domino-piece'>🁣</div>"
    , "      <h1 class='game-title'>"
    , "        <span class='title-domino'>Domino's</span>"
    , "        <span class='title-piza'>PizA</span>"
    , "      </h1>"
    , "      <div class='domino-piece'>🁩</div>"
    , "    </div>"
    , "    <p class='bouncy-text'>"
    , "      <span style='animation-delay: 0s'>J</span>"
    , "      <span style='animation-delay: 0.1s'>u</span>"
    , "      <span style='animation-delay: 0.2s'>e</span>"
    , "      <span style='animation-delay: 0.3s'>g</span>"
    , "      <span style='animation-delay: 0.4s'>o</span>"
    , "      <span style='animation-delay: 0.5s'> </span>"
    , "      <span style='animation-delay: 0.6s'>d</span>"
    , "      <span style='animation-delay: 0.7s'>e</span>"
    , "      <span style='animation-delay: 0.8s'> </span>"
    , "      <span style='animation-delay: 0.9s'>d</span>"
    , "      <span style='animation-delay: 1.0s'>o</span>"
    , "      <span style='animation-delay: 1.1s'>m</span>"
    , "      <span style='animation-delay: 1.2s'>i</span>"
    , "      <span style='animation-delay: 1.3s'>n</span>"
    , "      <span style='animation-delay: 1.4s'>o</span>"
    , "      <span style='animation-delay: 1.5s'> </span>"
    , "      <span style='animation-delay: 1.6s'>e</span>"
    , "      <span style='animation-delay: 1.7s'>n</span>"
    , "      <span style='animation-delay: 1.8s'> </span>"
    , "      <span style='animation-delay: 1.9s'>H</span>"
    , "      <span style='animation-delay: 2.0s'>a</span>"
    , "      <span style='animation-delay: 2.1s'>s</span>"
    , "      <span style='animation-delay: 2.2s'>k</span>"
    , "      <span style='animation-delay: 2.3s'>e</span>"
    , "      <span style='animation-delay: 2.4s'>l</span>"
    , "      <span style='animation-delay: 2.5s'>l</span>"
    , "    </p>"
    , "    <div class='menu-buttons'>"
    , "      <button onclick=\"showGameSetup()\" class='btn-start'>▶️ Jugar</button>"
    , "      <button onclick=\"exitGame()\" class='btn-exit'>❌ Salir</button>"
    , "    </div>"
    , "  </div>"
    , ""
    , "  <div class='container hidden' id='game-setup'>"
    , "    <h1>🎮 Configuración</h1>"
    , "    <div class='setup-container'>"
    , "      <!-- Modo de Juego -->"
    , "      <div class='setup-section'>"
    , "        <h3>Modo de Juego</h3>"
    , "        <div class='selector-group'>"
    , "          <button onclick=\"selectGameMode('robadito')\" id='btn-robadito' class='btn-selector active'>🎴 Robadito</button>"
    , "          <button onclick=\"selectGameMode('norobadito')\" id='btn-norobadito' class='btn-selector'>🚫 Sin Robar</button>"
    , "        </div>"
    , "      </div>"
    , ""
    , "      <!-- Modo VS -->"
    , "      <div class='setup-section'>"
    , "        <h3>Modo de Juego</h3>"
    , "        <div class='selector-group'>"
    , "          <button onclick=\"selectVsMode('1vs1')\" id='btn-1vs1' class='btn-selector'>👤 1 vs 1</button>"
    , "          <button onclick=\"selectVsMode('freeforall')\" id='btn-freeforall' class='btn-selector active'>👥 Todos vs Todos</button>"
    , "          <button onclick=\"selectVsMode('2vs2')\" id='btn-2vs2' class='btn-selector disabled' disabled>👥👥 2 vs 2 🔒</button>"
    , "        </div>"
    , "      </div>"
    , ""
    , "      <!-- Dificultad -->"
    , "      <div class='setup-section'>"
    , "        <h3>Dificultad de la IA</h3>"
    , "        <div class='selector-group'>"
    , "          <button onclick=\"selectDifficulty('easy')\" id='btn-easy' class='btn-selector btn-diff-easy active'>😊 Fácil</button>"
    , "          <button onclick=\"selectDifficulty('medium')\" id='btn-medium' class='btn-selector btn-diff-medium'>🤔 Medio</button>"
    , "          <button onclick=\"selectDifficulty('hard')\" id='btn-hard' class='btn-selector btn-diff-hard'>😈 Difícil</button>"
    , "        </div>"
    , "      </div>"
    , ""
    , "      <div class='setup-actions'>"
    , "        <button onclick=\"startGame()\" class='btn-start-game'>🚀 Iniciar Partida</button>"
    , "        <button onclick=\"backToMenu()\" class='btn-back'>⬅️ Volver</button>"
    , "      </div>"
    , "    </div>"
    , "  </div>"
    , ""
    , "  <script>"
    , "    let gameConfig = {"
    , "      gameMode: 'robadito',"
    , "      vsMode: 'freeforall',"
    , "      difficulty: 'easy'"
    , "    };"
    , ""
    , "    function showGameSetup() {"
    , "      document.getElementById('main-menu').classList.add('hidden');"
    , "      document.getElementById('game-setup').classList.remove('hidden');"
    , "    }"
    , ""
    , "    function backToMenu() {"
    , "      document.getElementById('game-setup').classList.add('hidden');"
    , "      document.getElementById('main-menu').classList.remove('hidden');"
    , "    }"
    , ""
    , "    function exitGame() {"
    , "      if (confirm('Seguro que quieres salir?')) {"
    , "        document.body.innerHTML = ''"
    , "          + '<div class=\"exit-screen\">'"
    , "          + '<div class=\"exit-content\">'"
    , "          + '<div class=\"exit-dominos\">🁣 🁩</div>'"
    , "          + '<h1 class=\"exit-title\">Gracias por jugar!</h1>'"
    , "          + '<p class=\"exit-subtitle\">Dominos PizA</p>'"
    , "          + '<p class=\"exit-message\">Puedes cerrar esta pestana o</p>'"
    , "          + '<button onclick=\"location.reload()\" class=\"exit-btn\">Volver a jugar</button>'"
    , "          + '</div>'"
    , "          + '</div>';"
    , "      }"
    , "    }"
    , ""
    , "    function selectGameMode(mode) {"
    , "      gameConfig.gameMode = mode;"
    , "      document.getElementById('btn-robadito').classList.toggle('active', mode === 'robadito');"
    , "      document.getElementById('btn-norobadito').classList.toggle('active', mode === 'norobadito');"
    , "    }"
    , ""
    , "    function selectVsMode(mode) {"
    , "      if (mode === '2vs2') return;"
    , "      gameConfig.vsMode = mode;"
    , "      document.getElementById('btn-1vs1').classList.toggle('active', mode === '1vs1');"
    , "      document.getElementById('btn-freeforall').classList.toggle('active', mode === 'freeforall');"
    , "      document.getElementById('btn-2vs2').classList.toggle('active', mode === '2vs2');"
    , "    }"
    , ""
    , "    function selectDifficulty(diff) {"
    , "      gameConfig.difficulty = diff;"
    , "      document.getElementById('btn-easy').classList.toggle('active', diff === 'easy');"
    , "      document.getElementById('btn-medium').classList.toggle('active', diff === 'medium');"
    , "      document.getElementById('btn-hard').classList.toggle('active', diff === 'hard');"
    , "    }"
    , "    function startGame() {"
    , "      localStorage.setItem('domino-config', JSON.stringify(gameConfig));"
    , "      location.href = '/game';"
    , "    }"
    , "  </script>"
    , "</body>"
    , "</html>"
    ]

-- | Página del juego
gameHtml :: Text
gameHtml = TL.concat
    [ "<!DOCTYPE html>"
    , "<html lang='es'>"
    , "<head>"
    , "  <meta charset='UTF-8'>"
    , "  <meta name='viewport' content='width=device-width, initial-scale=1.0'>"
    , "  <title>Dominó - Partida</title>"
    , "  <style>", cssStyles, "</style>"
    , "</head>"
    , "<body>"
    , "  <div class='game-container'>"
    , "    <header>"
    , "      <h1>🎲 Dominó</h1>"
    , "      <div id='message' class='message'></div>"
    , "    </header>"
    , "    "
    , "    <div class='players-info'>"
    , "      <div id='players'></div>"
    , "    </div>"
    , "    "
    , "    <div class='board-container'>"
    , "      <h3>Mesa</h3>"
    , "      <div id='board' class='board'></div>"
    , "    </div>"
    , "    "
    , "    <div class='hand-container'>"
    , "      <h3>Tu mano <span id='hand-count'></span></h3>"
    , "      <div id='hand' class='hand'></div>"
    , "    </div>"
    , "    "
    , "    <div class='actions'>"
    , "      <button id='btn-draw' class='btn' onclick='drawTile()'>🎴 Robar</button>"
    , "      <button id='btn-pass' class='btn' onclick='passTurn()'>⏭️ Pasar</button>"
    , "      <button class='btn btn-new' onclick='newGame()'>🔄 Nueva Partida</button>"
    , "      <button class='btn btn-menu' onclick='goToMenu()'>🏠 Menú</button>"
    , "    </div>"
    , "    "
    , "    <div id='side-selector' class='side-selector hidden'>"
    , "      <p>¿En qué lado quieres jugar?</p>"
    , "      <button class='btn' onclick='playSelected(\"left\")'>⬅️ Izquierda</button>"
    , "      <button class='btn' onclick='playSelected(\"right\")'>➡️ Derecha</button>"
    , "      <button class='btn btn-cancel' onclick='cancelSelection()'>Cancelar</button>"
    , "    </div>"
    , "  </div>"
    , "  "
    , "  <div id='game-over-modal' class='modal hidden'>"
    , "    <div class='modal-content'>"
    , "      <h2>🎉 ¡Juego Terminado!</h2>"
    , "      <p id='winner-text'></p>"
    , "      <button class='btn btn-new' onclick='newGame()'>Nueva Partida</button>"
    , "    </div>"
    , "  </div>"
    , "  "
    , "  <script>", jsScript, "</script>"
    , "</body>"
    , "</html>"
    ]

-- | Estilos CSS
cssStyles :: Text
cssStyles = TL.concat
    [ "* { box-sizing: border-box; margin: 0; padding: 0; }"
    , "body { "
    , "  font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;"
    , "  background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);"
    , "  min-height: 100vh;"
    , "  color: #fff;"
    , "}"
    , ".container {"
    , "  display: flex;"
    , "  flex-direction: column;"
    , "  align-items: center;"
    , "  justify-content: center;"
    , "  min-height: 100vh;"
    , "  text-align: center;"
    , "}"
    , ".container h1 { font-size: 4rem; margin-bottom: 1rem; }"
    , ".container p { font-size: 1.2rem; margin-bottom: 2rem; color: #aaa; }"
    , ".btn-start {"
    , "  padding: 1rem 3rem;"
    , "  font-size: 1.5rem;"
    , "  background: linear-gradient(45deg, #e94560, #ff6b6b);"
    , "  border: none;"
    , "  border-radius: 50px;"
    , "  color: white;"
    , "  cursor: pointer;"
    , "  transition: transform 0.3s, box-shadow 0.3s;"
    , "}"
    , ".btn-start:hover {"
    , "  transform: scale(1.05);"
    , "  box-shadow: 0 10px 30px rgba(233, 69, 96, 0.4);"
    , "}"
    , ".game-container {"
    , "  max-width: 1200px;"
    , "  margin: 0 auto;"
    , "  padding: 1rem;"
    , "}"
    , "header {"
    , "  text-align: center;"
    , "  padding: 1.5rem;"
    , "}"
    , "header h1 { font-size: 2.5rem; }"
    , ".message {"
    , "  background: rgba(255,255,255,0.1);"
    , "  padding: 0.5rem 1rem;"
    , "  border-radius: 10px;"
    , "  margin-top: 0.5rem;"
    , "  font-size: 1.1rem;"
    , "}"
    , ".players-info {"
    , "  display: flex;"
    , "  flex-direction: row;"
    , "  justify-content: center;"
    , "  align-items: center;"
    , "  gap: 1.5rem;"
    , "  flex-wrap: nowrap;"
    , "  margin: 1.5rem auto;"
    , "  padding: 1rem;"
    , "  overflow-x: auto;"
    , "}"
    , ".player-card {"
    , "  background: rgba(255,255,255,0.1);"
    , "  padding: 0.8rem 1.5rem;"
    , "  border-radius: 12px;"
    , "  min-width: 120px;"
    , "  text-align: center;"
    , "  flex-shrink: 0;"
    , "}"
    , ".player-card.active {"
    , "  background: linear-gradient(45deg, #e94560, #ff6b6b);"
    , "  box-shadow: 0 5px 20px rgba(233, 69, 96, 0.4);"
    , "}"
    , ".player-card .name { font-weight: bold; }"
    , ".player-card .count { font-size: 0.9rem; opacity: 0.8; }"
    , ".board-container {"
    , "  background: linear-gradient(145deg, #2d5016, #1a3009);"
    , "  border-radius: 25px;"
    , "  padding: 2rem;"
    , "  margin: 1.5rem auto;"
    , "  min-height: 280px;"
    , "  max-width: 95%;"
    , "  box-shadow: inset 0 8px 30px rgba(0,0,0,0.4), 0 10px 40px rgba(0,0,0,0.3);"
    , "  border: 4px solid #3d6620;"
    , "}"
    , ".board-container h3 {"
    , "  text-align: center;"
    , "  margin-bottom: 1.5rem;"
    , "  color: #90EE90;"
    , "  font-size: 1.5rem;"
    , "}"
    , ".board {"
    , "  display: flex;"
    , "  flex-wrap: wrap;"
    , "  justify-content: center;"
    , "  align-items: center;"
    , "  gap: 6px;"
    , "  min-height: 150px;"
    , "  padding: 1.5rem;"
    , "}"
    , ".hand-container {"
    , "  background: rgba(255,255,255,0.08);"
    , "  border-radius: 25px;"
    , "  padding: 2rem;"
    , "  margin: 1.5rem auto;"
    , "  max-width: 95%;"
    , "  border: 2px solid rgba(255,255,255,0.1);"
    , "}"
    , ".hand-container h3 {"
    , "  text-align: center;"
    , "  margin-bottom: 1.5rem;"
    , "  font-size: 1.4rem;"
    , "}"
    , ".hand {"
    , "  display: flex;"
    , "  flex-wrap: wrap;"
    , "  justify-content: center;"
    , "  gap: 12px;"
    , "}"
    , ".domino {"
    , "  background: linear-gradient(145deg, #fff, #e0e0e0);"
    , "  border-radius: 10px;"
    , "  display: flex;"
    , "  box-shadow: 3px 3px 12px rgba(0,0,0,0.4);"
    , "  cursor: pointer;"
    , "  transition: transform 0.2s, box-shadow 0.2s;"
    , "}"
    , ".domino:hover {"
    , "  transform: translateY(-8px);"
    , "  box-shadow: 6px 12px 24px rgba(0,0,0,0.5);"
    , "}"
    , ".domino.selected {"
    , "  box-shadow: 0 0 30px #00ff00;"
    , "  transform: translateY(-12px);"
    , "}"
    , ".domino.horizontal {"
    , "  flex-direction: row;"
    , "  width: 100px;"
    , "  height: 50px;"
    , "}"
    , ".domino.vertical {"
    , "  flex-direction: column;"
    , "  width: 50px;"
    , "  height: 100px;"
    , "}"
    , ".domino-half {"
    , "  flex: 1;"
    , "  display: flex;"
    , "  justify-content: center;"
    , "  align-items: center;"
    , "  font-weight: bold;"
    , "  color: #333;"
    , "  font-size: 18px;"
    , "  position: relative;"
    , "}"
    , ".domino.horizontal .domino-half {"
    , "  border-right: 2px solid #999;"
    , "}"
    , ".domino.horizontal .domino-half:last-child {"
    , "  border-right: none;"
    , "}"
    , ".domino.vertical .domino-half {"
    , "  border-bottom: 2px solid #999;"
    , "}"
    , ".domino.vertical .domino-half:last-child {"
    , "  border-bottom: none;"
    , "}"
    , ".domino.board-tile {"
    , "  cursor: default;"
    , "  transform: none;"
    , "}"
    , ".domino.board-tile:hover {"
    , "  transform: none;"
    , "}"
    , ".domino.double {"
    , "  flex-direction: column;"
    , "  width: 35px;"
    , "  height: 70px;"
    , "}"
    , ".actions {"
    , "  display: flex;"
    , "  justify-content: center;"
    , "  gap: 1rem;"
    , "  margin: 1rem 0;"
    , "  flex-wrap: wrap;"
    , "}"
    , ".btn {"
    , "  padding: 0.8rem 1.5rem;"
    , "  font-size: 1rem;"
    , "  background: rgba(255,255,255,0.1);"
    , "  border: 1px solid rgba(255,255,255,0.2);"
    , "  border-radius: 10px;"
    , "  color: white;"
    , "  cursor: pointer;"
    , "  transition: all 0.3s;"
    , "}"
    , ".btn:hover {"
    , "  background: rgba(255,255,255,0.2);"
    , "}"
    , ".btn:disabled {"
    , "  opacity: 0.5;"
    , "  cursor: not-allowed;"
    , "}"
    , ".btn-new {"
    , "  background: linear-gradient(45deg, #e94560, #ff6b6b);"
    , "  border: none;"
    , "}"
    , ".btn-menu {"
    , "  background: linear-gradient(45deg, #2196F3, #03A9F4);"
    , "  border: none;"
    , "}"
    , ".btn-cancel {"
    , "  background: rgba(255,0,0,0.3);"
    , "}"
    , ".side-selector {"
    , "  position: fixed;"
    , "  bottom: 20px;"
    , "  left: 50%;"
    , "  transform: translateX(-50%);"
    , "  background: rgba(0,0,0,0.9);"
    , "  padding: 1rem 2rem;"
    , "  border-radius: 15px;"
    , "  text-align: center;"
    , "  z-index: 100;"
    , "  box-shadow: 0 10px 40px rgba(0,0,0,0.5);"
    , "}"
    , ".side-selector p { margin-bottom: 1rem; }"
    , ".hidden { display: none !important; }"
    , ".modal {"
    , "  position: fixed;"
    , "  top: 0;"
    , "  left: 0;"
    , "  width: 100%;"
    , "  height: 100%;"
    , "  background: rgba(0,0,0,0.8);"
    , "  display: flex;"
    , "  justify-content: center;"
    , "  align-items: center;"
    , "  z-index: 1000;"
    , "}"
    , ".modal-content {"
    , "  background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);"
    , "  padding: 3rem;"
    , "  border-radius: 20px;"
    , "  text-align: center;"
    , "  box-shadow: 0 20px 60px rgba(0,0,0,0.5);"
    , "}"
    , ".modal-content h2 { font-size: 2rem; margin-bottom: 1rem; }"
    , ".modal-content p { margin-bottom: 2rem; font-size: 1.2rem; }"
    , ".exit-screen {"
    , "  position: fixed;"
    , "  top: 0;"
    , "  left: 0;"
    , "  width: 100%;"
    , "  height: 100%;"
    , "  background: linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%);"
    , "  display: flex;"
    , "  justify-content: center;"
    , "  align-items: center;"
    , "}"
    , ".exit-content {"
    , "  text-align: center;"
    , "  animation: fadeIn 0.5s ease-out;"
    , "}"
    , "@keyframes fadeIn {"
    , "  from { opacity: 0; transform: scale(0.8); }"
    , "  to { opacity: 1; transform: scale(1); }"
    , "}"
    , ".exit-dominos {"
    , "  font-size: 6rem;"
    , "  margin-bottom: 2rem;"
    , "  animation: float 3s ease-in-out infinite;"
    , "}"
    , "@keyframes float {"
    , "  0%, 100% { transform: translateY(0); }"
    , "  50% { transform: translateY(-20px); }"
    , "}"
    , ".exit-title {"
    , "  font-size: 3.5rem;"
    , "  color: #fff;"
    , "  margin-bottom: 1rem;"
    , "  background: linear-gradient(45deg, #FFD700, #FFA500);"
    , "  -webkit-background-clip: text;"
    , "  -webkit-text-fill-color: transparent;"
    , "  background-clip: text;"
    , "}"
    , ".exit-subtitle {"
    , "  font-size: 1.8rem;"
    , "  color: #00CED1;"
    , "  margin-bottom: 2rem;"
    , "  font-style: italic;"
    , "}"
    , ".exit-message {"
    , "  font-size: 1.2rem;"
    , "  color: #aaa;"
    , "  margin-bottom: 1.5rem;"
    , "}"
    , ".exit-btn {"
    , "  padding: 1rem 3rem;"
    , "  font-size: 1.3rem;"
    , "  background: linear-gradient(45deg, #4CAF50, #8BC34A);"
    , "  border: none;"
    , "  border-radius: 50px;"
    , "  color: white;"
    , "  cursor: pointer;"
    , "  transition: transform 0.3s, box-shadow 0.3s;"
    , "  font-weight: bold;"
    , "}"
    , ".exit-btn:hover {"
    , "  transform: scale(1.1);"
    , "  box-shadow: 0 10px 40px rgba(76, 175, 80, 0.5);"
    , "}"
    , ".pip {"
    , "  width: 8px;"
    , "  height: 8px;"
    , "  background: #333;"
    , "  border-radius: 50%;"
    , "  position: absolute;"
    , "}"
    ]

-- | Estilos adicionales para la página de inicio
indexCssStyles :: Text
indexCssStyles = TL.concat
    [ "@keyframes bounce {"
    , "  0%, 100% { transform: translateY(0); }"
    , "  50% { transform: translateY(-15px); }"
    , "}"
    , "@keyframes glow {"
    , "  0%, 100% { text-shadow: 0 0 10px #ff6b6b, 0 0 20px #ff6b6b, 0 0 30px #ff6b6b; }"
    , "  50% { text-shadow: 0 0 20px #ffd700, 0 0 40px #ffd700, 0 0 60px #ffd700; }"
    , "}"
    , "@keyframes rotate {"
    , "  0% { transform: rotate(-10deg); }"
    , "  50% { transform: rotate(10deg); }"
    , "  100% { transform: rotate(-10deg); }"
    , "}"
    , ".title-container {"
    , "  display: flex;"
    , "  align-items: center;"
    , "  justify-content: center;"
    , "  gap: 1rem;"
    , "  margin-bottom: 1rem;"
    , "}"
    , ".domino-piece {"
    , "  font-size: 4rem;"
    , "  animation: rotate 2s ease-in-out infinite;"
    , "  filter: drop-shadow(0 0 10px rgba(255,255,255,0.5));"
    , "}"
    , ".game-title {"
    , "  font-size: 3.5rem;"
    , "  font-family: 'Georgia', serif;"
    , "  letter-spacing: 3px;"
    , "  margin: 0;"
    , "}"
    , ".title-domino {"
    , "  background: linear-gradient(45deg, #FFD700, #FFA500, #FF6347);"
    , "  -webkit-background-clip: text;"
    , "  -webkit-text-fill-color: transparent;"
    , "  background-clip: text;"
    , "  font-weight: bold;"
    , "  text-shadow: none;"
    , "  filter: drop-shadow(2px 2px 4px rgba(0,0,0,0.5));"
    , "}"
    , ".title-piza {"
    , "  background: linear-gradient(45deg, #00CED1, #20B2AA, #48D1CC);"
    , "  -webkit-background-clip: text;"
    , "  -webkit-text-fill-color: transparent;"
    , "  background-clip: text;"
    , "  font-style: italic;"
    , "  font-weight: bold;"
    , "  filter: drop-shadow(2px 2px 4px rgba(0,0,0,0.5));"
    , "}"
    , ".bouncy-text {"
    , "  font-size: 1.3rem;"
    , "  color: #90EE90;"
    , "  margin: 1.5rem 0;"
    , "}"
    , ".bouncy-text span {"
    , "  display: inline-block;"
    , "  animation: bounce 2s ease-in-out infinite;"
    , "}"
    , ".menu-buttons {"
    , "  display: flex;"
    , "  gap: 2rem;"
    , "  margin-top: 3rem;"
    , "}"
    , ".btn-start {"
    , "  padding: 1.5rem 3rem;"
    , "  font-size: 1.5rem;"
    , "  background: linear-gradient(45deg, #4CAF50, #8BC34A);"
    , "  border: none;"
    , "  border-radius: 15px;"
    , "  color: white;"
    , "  cursor: pointer;"
    , "  transition: transform 0.3s, box-shadow 0.3s;"
    , "  font-weight: bold;"
    , "}"
    , ".btn-start:hover {"
    , "  transform: scale(1.05);"
    , "  box-shadow: 0 10px 30px rgba(76, 175, 80, 0.5);"
    , "}"
    , ".btn-exit {"
    , "  padding: 1.5rem 3rem;"
    , "  font-size: 1.5rem;"
    , "  background: linear-gradient(45deg, #f44336, #E91E63);"
    , "  border: none;"
    , "  border-radius: 15px;"
    , "  color: white;"
    , "  cursor: pointer;"
    , "  transition: transform 0.3s, box-shadow 0.3s;"
    , "  font-weight: bold;"
    , "}"
    , ".btn-exit:hover {"
    , "  transform: scale(1.05);"
    , "  box-shadow: 0 10px 30px rgba(244, 67, 54, 0.5);"
    , "}"
    , ".setup-container {"
    , "  background: rgba(255,255,255,0.05);"
    , "  border-radius: 20px;"
    , "  padding: 2rem;"
    , "  max-width: 600px;"
    , "  margin: 0 auto;"
    , "}"
    , ".setup-section {"
    , "  margin-bottom: 2rem;"
    , "}"
    , ".setup-section h3 {"
    , "  margin-bottom: 1rem;"
    , "  color: #90EE90;"
    , "}"
    , ".selector-group {"
    , "  display: flex;"
    , "  gap: 1rem;"
    , "  flex-wrap: wrap;"
    , "  justify-content: center;"
    , "}"
    , ".btn-selector {"
    , "  padding: 1rem 1.5rem;"
    , "  font-size: 1.1rem;"
    , "  background: rgba(255,255,255,0.1);"
    , "  border: 2px solid rgba(255,255,255,0.2);"
    , "  border-radius: 10px;"
    , "  color: white;"
    , "  cursor: pointer;"
    , "  transition: all 0.3s;"
    , "}"
    , ".btn-selector:hover:not(.disabled) {"
    , "  background: rgba(255,255,255,0.2);"
    , "  transform: translateY(-3px);"
    , "}"
    , ".btn-selector.active {"
    , "  background: linear-gradient(45deg, #e94560, #ff6b6b);"
    , "  border-color: #ff6b6b;"
    , "  box-shadow: 0 5px 20px rgba(233, 69, 96, 0.4);"
    , "}"
    , ".btn-selector.disabled {"
    , "  opacity: 0.4;"
    , "  cursor: not-allowed;"
    , "}"
    , ".btn-diff-easy.active {"
    , "  background: linear-gradient(45deg, #4CAF50, #8BC34A);"
    , "  border-color: #8BC34A;"
    , "  box-shadow: 0 5px 20px rgba(76, 175, 80, 0.4);"
    , "}"
    , ".btn-diff-medium.active {"
    , "  background: linear-gradient(45deg, #FF9800, #FFC107);"
    , "  border-color: #FFC107;"
    , "  box-shadow: 0 5px 20px rgba(255, 152, 0, 0.4);"
    , "}"
    , ".btn-diff-hard.active {"
    , "  background: linear-gradient(45deg, #f44336, #E91E63);"
    , "  border-color: #E91E63;"
    , "  box-shadow: 0 5px 20px rgba(244, 67, 54, 0.4);"
    , "}"
    , ".setup-actions {"
    , "  display: flex;"
    , "  gap: 1rem;"
    , "  justify-content: center;"
    , "  margin-top: 2rem;"
    , "}"
    , ".btn-start-game {"
    , "  padding: 1rem 2rem;"
    , "  font-size: 1.3rem;"
    , "  background: linear-gradient(45deg, #4CAF50, #8BC34A);"
    , "  border: none;"
    , "  border-radius: 10px;"
    , "  color: white;"
    , "  cursor: pointer;"
    , "  transition: all 0.3s;"
    , "  font-weight: bold;"
    , "}"
    , ".btn-start-game:hover {"
    , "  transform: scale(1.05);"
    , "  box-shadow: 0 10px 30px rgba(76, 175, 80, 0.5);"
    , "}"
    , ".btn-back {"
    , "  padding: 1rem 2rem;"
    , "  font-size: 1.3rem;"
    , "  background: rgba(255,255,255,0.1);"
    , "  border: 2px solid rgba(255,255,255,0.2);"
    , "  border-radius: 10px;"
    , "  color: white;"
    , "  cursor: pointer;"
    , "  transition: all 0.3s;"
    , "}"
    , ".btn-back:hover {"
    , "  background: rgba(255,255,255,0.2);"
    , "}"
    , ".difficulty-selector {"
    , "  margin-top: 3rem;"
    , "  display: flex;"
    , "  flex-direction: column;"
    , "  align-items: center;"
    , "  gap: 2rem;"
    , "}"
    , ".difficulty-selector h2 {"
    , "  font-size: 1.8rem;"
    , "  margin-bottom: 0;"
    , "}"
    , ".difficulty-buttons {"
    , "  display: flex;"
    , "  gap: 2rem;"
    , "  flex-wrap: wrap;"
    , "  justify-content: center;"
    , "}"
    , ".btn-difficulty {"
    , "  padding: 1.5rem 3rem;"
    , "  font-size: 1.5rem;"
    , "  border: none;"
    , "  border-radius: 15px;"
    , "  color: white;"
    , "  cursor: pointer;"
    , "  transition: transform 0.3s, box-shadow 0.3s;"
    , "  font-weight: bold;"
    , "  min-width: 200px;"
    , "}"
    , ".btn-easy {"
    , "  background: linear-gradient(45deg, #4CAF50, #8BC34A);"
    , "}"
    , ".btn-easy:hover {"
    , "  transform: scale(1.05);"
    , "  box-shadow: 0 10px 30px rgba(76, 175, 80, 0.5);"
    , "}"
    , ".btn-medium {"
    , "  background: linear-gradient(45deg, #FF9800, #FFC107);"
    , "}"
    , ".btn-medium:hover {"
    , "  transform: scale(1.05);"
    , "  box-shadow: 0 10px 30px rgba(255, 152, 0, 0.5);"
    , "}"
    , ".btn-hard {"
    , "  background: linear-gradient(45deg, #f44336, #E91E63);"
    , "}"
    , ".btn-hard:hover {"
    , "  transform: scale(1.05);"
    , "  box-shadow: 0 10px 30px rgba(244, 67, 54, 0.5);"
    , "}"
    ]

-- | JavaScript del juego
jsScript :: Text
jsScript = TL.unlines
    [ "let gameState = null;"
    , "let selectedDomino = null;"
    , "let controlled = '0'; // '0','1','2','3' or 'all'"
    , "function onControlChange(v) { controlled = v; render(); }"
    , ""
    , "async function fetchState() {"
    , "  const res = await fetch('/api/state');"
    , "  gameState = await res.json();"
    , "  console.log('Estado recibido:', gameState);"
    , "  console.log('Mano jugador 0:', gameState.grPlayers[0].pjHand);"
    , "  render();"
    , "}"
    , ""
    , "async function newGame() {"
    , "  const configStr = localStorage.getItem('domino-config');"
    , "  let config = { gameMode: 'robadito', vsMode: 'freeforall', difficulty: 'easy' };"
    , "  if (configStr) {"
    , "    try { config = JSON.parse(configStr); } catch(e) {}"
    , "  }"
    , "  const res = await fetch('/api/new', { "
    , "    method: 'POST',"
    , "    headers: { 'Content-Type': 'application/json' },"
    , "    body: JSON.stringify(config)"
    , "  });"
    , "  gameState = await res.json();"
    , "  selectedDomino = null;"
    , "  document.getElementById('game-over-modal').classList.add('hidden');"
    , "  render();"
    , "}"
    , ""
    , "async function playTile(domino, side) {"
    , "  const res = await fetch('/api/play', {"
    , "    method: 'POST',"
    , "    headers: { 'Content-Type': 'application/json' },"
    , "    body: JSON.stringify({ action: 'play', domino: domino, side: side })"
    , "  });"
    , "  gameState = await res.json();"
    , "  selectedDomino = null;"
    , "  render();"
    , "}"
    , ""
    , "async function drawTile() {"
    , "  const res = await fetch('/api/play', {"
    , "    method: 'POST',"
    , "    headers: { 'Content-Type': 'application/json' },"
    , "    body: JSON.stringify({ action: 'draw', domino: null, side: null })"
    , "  });"
    , "  gameState = await res.json();"
    , "  render();"
    , "}"
    , ""
    , "async function passTurn() {"
    , "  const res = await fetch('/api/play', {"
    , "    method: 'POST',"
    , "    headers: { 'Content-Type': 'application/json' },"
    , "    body: JSON.stringify({ action: 'pass', domino: null, side: null })"
    , "  });"
    , "  gameState = await res.json();"
    , "  render();"
    , "}"
    , ""
    , "function isControlledTurn() { return controlled === 'all' || (parseInt(controlled) === gameState.grCurrentPlayer); }"
    , "function selectDomino(domino) {"
    , "  if (gameState.grGameOver) return;"
    , "  if (!isControlledTurn()) {"
    , "    alert('No es tu turno (control seleccionado). Cambia el control para jugar este jugador.');"
    , "    return;"
    , "  }"
    , "  selectedDomino = domino;"
    , "  "
    , "  // Si el tablero está vacío, jugar automáticamente"
    , "  if (gameState.grBoard.bjTiles.length === 0) {"
    , "    playTile(domino, 'right');"
    , "    return;"
    , "  }"
    , "  "
    , "  // Mostrar selector de lado"
    , "  document.getElementById('side-selector').classList.remove('hidden');"
    , "  render();"
    , "}"
    , ""
    , "function playSelected(side) {"
    , "  if (selectedDomino) {"
    , "    playTile(selectedDomino, side);"
    , "  }"
    , "  document.getElementById('side-selector').classList.add('hidden');"
    , "}"
    , ""
    , "function cancelSelection() {"
    , "  selectedDomino = null;"
    , "  document.getElementById('side-selector').classList.add('hidden');"
    , "  render();"
    , "}"
    , ""
    , "function goToMenu() {"
    , "  location.href = '/';"
    , "}"
    , ""
    , "function createDominoElement(domino, isDouble, isBoard) {"
    , "  const div = document.createElement('div');"
    , "  const classes = ['domino'];"
    , "  "
    , "  if (isBoard) {"
    , "    classes.push('board-tile');"
    , "    classes.push(isDouble ? 'vertical' : 'horizontal');"
    , "  } else {"
    , "    classes.push('vertical');"
    , "    if (selectedDomino && selectedDomino.left === domino.left && selectedDomino.right === domino.right) {"
    , "      classes.push('selected');"
    , "    }"
    , "  }"
    , "  "
    , "  div.className = classes.join(' ');"
    , "  "
    , "  const half1 = document.createElement('div');"
    , "  half1.className = 'domino-half';"
    , "  half1.innerHTML = renderPips(domino.left);"
    , "  "
    , "  const half2 = document.createElement('div');"
    , "  half2.className = 'domino-half';"
    , "  half2.innerHTML = renderPips(domino.right);"
    , "  "
    , "  div.appendChild(half1);"
    , "  div.appendChild(half2);"
    , "  "
    , "  if (!isBoard) {"
    , "    div.onclick = () => selectDomino(domino);"
    , "  }"
    , "  "
    , "  return div;"
    , "}"
    , ""
    , "function renderPips(n) {"
    , "  const positions = {"
    , "    0: [],"
    , "    1: [[50, 50]],"
    , "    2: [[25, 25], [75, 75]],"
    , "    3: [[25, 25], [50, 50], [75, 75]],"
    , "    4: [[25, 25], [75, 25], [25, 75], [75, 75]],"
    , "    5: [[25, 25], [75, 25], [50, 50], [25, 75], [75, 75]],"
    , "    6: [[25, 25], [25, 50], [25, 75], [75, 25], [75, 50], [75, 75]],"
    , "    7: [[25, 25], [25, 50], [25, 75], [50, 50], [75, 25], [75, 50], [75, 75]],"
    , "    8: [[25, 25], [25, 50], [25, 75], [50, 25], [50, 75], [75, 25], [75, 50], [75, 75]],"
    , "    9: [[25, 25], [25, 50], [25, 75], [50, 25], [50, 50], [50, 75], [75, 25], [75, 50], [75, 75]]"
    , "  };"
    , "  return (positions[n] || []).map(([x, y]) => "
    , "    `<span class='pip' style='left:${x}%;top:${y}%;transform:translate(-50%,-50%)'></span>`"
    , "  ).join('');"
    , "}"
    , ""
    , "function render() {"
    , "  if (!gameState) return;"
    , "  "
    , "  // Mensaje"
    , "  document.getElementById('message').textContent = gameState.grMessage;"
    , "  "
    , "  // Jugadores"
    , "  const playersDiv = document.getElementById('players');"
    , "  playersDiv.innerHTML = gameState.grPlayers.map((p, i) => `"
    , "    <div class='player-card ${i === gameState.grCurrentPlayer ? 'active' : ''}'>"
    , "      <div class='name'>${p.pjName}</div>"
    , "      <div class='count'>${p.pjHandCount} fichas</div>"
    , "    </div>"
    , "  `).join('');"
    , "  playersDiv.innerHTML += `<div class='player-card'><div class='name'>Pozo</div><div class='count'>${gameState.grPozoCount} fichas</div></div>`;"
    , "  "
    , "  // Tablero"
    , "  const boardDiv = document.getElementById('board');"
    , "  boardDiv.innerHTML = '';"
    , "  if (gameState.grBoard.bjTiles.length === 0) {"
    , "    boardDiv.innerHTML = '<p style=\"color: #90EE90;\">Mesa vacía - Juega la primera ficha</p>';"
    , "  } else {"
    , "    gameState.grBoard.bjTiles.forEach(tile => {"
    , "      const isDouble = tile.left === tile.right;"
    , "      boardDiv.appendChild(createDominoElement(tile, isDouble, true));"
    , "    });"
    , "  }"
    , "  "
    , "  // Mano del jugador (según control seleccionado)"
    , "  const handDiv = document.getElementById('hand');"
    , "  handDiv.innerHTML = '';"
    , "  const handIndex = (controlled === 'all') ? gameState.grCurrentPlayer : parseInt(controlled);"
    , "  const myHand = gameState.grPlayers[handIndex].pjHand;"
    , "  console.log('Renderizando mano:', myHand);"
    , "  console.log('Índice de mano:', handIndex);"
    , "  document.getElementById('hand-count').textContent = `(${myHand.length} fichas)`;"
    , "  myHand.forEach(tile => {"
    , "    console.log('Creando ficha:', tile);"
    , "    handDiv.appendChild(createDominoElement(tile, false, false));"
    , "  });"
    , "  "
    , "  // Botones (habilitados solo si es el turno del jugador controlado)"
    , "  const canPlay = (controlled === 'all' ? true : (parseInt(controlled) === gameState.grCurrentPlayer)) && !gameState.grGameOver;"
    , "  document.getElementById('btn-draw').disabled = !gameState.grCanDraw || !canPlay;"
    , "  document.getElementById('btn-pass').disabled = !canPlay;"
    , "  "
    , "  // Game over"
    , "  if (gameState.grGameOver) {"
    , "    document.getElementById('winner-text').textContent = gameState.grWinner ? "
    , "      `Ganador: ${gameState.grWinner}` : 'Empate';"
    , "    document.getElementById('game-over-modal').classList.remove('hidden');"
    , "  }"
    , "}"
    , ""
    , "// Auto-play para bots (jugadores 1, 2, 3)"
    , "setInterval(async () => {"
    , "  // Solo ejecutar autoplay cuando control está en '0' (modo normal)"
    , "  if (controlled !== '0') return;"
    , "  if (gameState && !gameState.grGameOver && gameState.grCurrentPlayer !== 0) {"
    , "    await fetch('/api/bot-play', { method: 'POST' });"
    , "    await fetchState();"
    , "  }"
    , "}, 1500);"
    , ""
    , "// Iniciar"
    , "newGame();"
    ]
