{-# LANGUAGE OverloadedStrings #-}

module Web.Views 
    ( indexHtml
    , gameHtml
    ) where

import Data.Text.Lazy (Text)
import qualified Data.Text.Lazy as TL

-- | Página principal
indexHtml :: Text
indexHtml = TL.concat
    [ "<!DOCTYPE html>"
    , "<html lang='es'>"
    , "<head>"
    , "  <meta charset='UTF-8'>"
    , "  <meta name='viewport' content='width=device-width, initial-scale=1.0'>"
    , "  <title>Dominó - Haskell</title>"
    , "  <style>", cssStyles, indexCssStyles, "</style>"
    , "</head>"
    , "<body>"
    , "  <div class='container' id='main-menu'>"
    , "    <div class='title-container'>"
    , "      <div class='domino-piece'>🁣</div>"
    , "      <h1 class='game-title'>"
    , "        <span class='title-domino'>Domino's</span>"
    , "        <span class='title-piza'>PizA</span>"
    , "      </h1>"
    , "      <div class='domino-piece'>🁩</div>"
    , "    </div>"
    , "    <p class='bouncy-text'>"
    , "      <span style='animation-delay: 0s'>J</span>"
    , "      <span style='animation-delay: 0.1s'>u</span>"
    , "      <span style='animation-delay: 0.2s'>e</span>"
    , "      <span style='animation-delay: 0.3s'>g</span>"
    , "      <span style='animation-delay: 0.4s'>o</span>"
    , "      <span style='animation-delay: 0.5s'> </span>"
    , "      <span style='animation-delay: 0.6s'>d</span>"
    , "      <span style='animation-delay: 0.7s'>e</span>"
    , "      <span style='animation-delay: 0.8s'> </span>"
    , "      <span style='animation-delay: 0.9s'>d</span>"
    , "      <span style='animation-delay: 1.0s'>o</span>"
    , "      <span style='animation-delay: 1.1s'>m</span>"
    , "      <span style='animation-delay: 1.2s'>i</span>"
    , "      <span style='animation-delay: 1.3s'>n</span>"
    , "      <span style='animation-delay: 1.4s'>o</span>"
    , "      <span style='animation-delay: 1.5s'> </span>"
    , "      <span style='animation-delay: 1.6s'>e</span>"
    , "      <span style='animation-delay: 1.7s'>n</span>"
    , "      <span style='animation-delay: 1.8s'> </span>"
    , "      <span style='animation-delay: 1.9s'>H</span>"
    , "      <span style='animation-delay: 2.0s'>a</span>"
    , "      <span style='animation-delay: 2.1s'>s</span>"
    , "      <span style='animation-delay: 2.2s'>k</span>"
    , "      <span style='animation-delay: 2.3s'>e</span>"
    , "      <span style='animation-delay: 2.4s'>l</span>"
    , "      <span style='animation-delay: 2.5s'>l</span>"
    , "    </p>"
    , "    <div class='menu-buttons'>"
    , "      <button onclick=\"showGameSetup()\" class='btn-start'>▶️ Jugar</button>"
    , "      <button onclick=\"exitGame()\" class='btn-exit'>❌ Salir</button>"
    , "    </div>"
    , "  </div>"
    , ""
    , "  <div class='container hidden' id='game-setup'>"
    , "    <h1>🎮 Configuración</h1>"
    , "    <div class='setup-container'>"
    , "      <!-- Modo de Juego -->"
    , "      <div class='setup-section'>"
    , "        <h3>Modo de Juego</h3>"
    , "        <div class='selector-group'>"
    , "          <button onclick=\"selectGameMode('robadito')\" id='btn-robadito' class='btn-selector active'>🎴 Robadito</button>"
    , "          <button onclick=\"selectGameMode('norobadito')\" id='btn-norobadito' class='btn-selector'>🚫 Sin Robar</button>"
    , "        </div>"
    , "      </div>"
    , ""
    , "      <!-- Modo VS -->"
    , "      <div class='setup-section'>"
    , "        <h3>Jugadores</h3>"
    , "        <div class='selector-group'>"
    , "          <button onclick=\"selectVsMode('1vs1')\" id='btn-1vs1' class='btn-selector'>👤 1 vs 1</button>"
    , "          <button onclick=\"selectVsMode('freeforall')\" id='btn-freeforall' class='btn-selector active'>👥 Todos vs Todos</button>"
    , "          <button onclick=\"selectVsMode('2vs2')\" id='btn-2vs2' class='btn-selector'>👥👥 2 vs 2</button>"
    , "        </div>"
    , "      </div>"
    , ""
    , "      <!-- Data a 100 (Solo para Sin Robar + 2vs2) -->"
    , "      <div class='setup-section data100-section hidden' id='data100-section'>"
    , "        <h3>🎯 Data a 100</h3>"
    , "        <div class='data100-toggle'>"
    , "          <label class='toggle-switch'>"
    , "            <input type='checkbox' id='data100-enabled' onchange='toggleData100()'>"
    , "            <span class='toggle-slider'></span>"
    , "          </label>"
    , "          <span>Activar modo Data a 100</span>"
    , "        </div>"
    , "        <div class='data100-options hidden' id='data100-options'>"
    , "          <div class='data100-target'>"
    , "            <label>Puntuación objetivo:</label>"
    , "            <select id='data100-target' onchange='updateData100Target()'>"
    , "              <option value='100'>100 puntos</option>"
    , "              <option value='150'>150 puntos</option>"
    , "              <option value='200'>200 puntos</option>"
    , "            </select>"
    , "          </div>"
    , "          <h4>⭐ Bonus</h4>"
    , "          <div class='bonus-options'>"
    , "            <label class='bonus-option'>"
    , "              <input type='checkbox' id='bonus-nosalida' onchange='updateData100Bonus()'>"
    , "              <span>🚫 No llevar salida (+20 puntos)</span>"
    , "            </label>"
    , "            <label class='bonus-option'>"
    , "              <input type='checkbox' id='bonus-primerdoble' onchange='updateData100Bonus()'>"
    , "              <span>🥇 Primer partido cuenta doble</span>"
    , "            </label>"
    , "            <label class='bonus-option'>"
    , "              <input type='checkbox' id='bonus-capicua' onchange='updateData100Bonus()'>"
    , "              <span>🔄 Capicúa cuenta doble</span>"
    , "            </label>"
    , "          </div>"
    , "        </div>"
    , "      </div>"
    , ""
    , "      <!-- Dificultad -->"
    , "      <div class='setup-section'>"
    , "        <h3>Dificultad de la IA</h3>"
    , "        <div class='selector-group'>"
    , "          <button onclick=\"selectDifficulty('easy')\" id='btn-easy' class='btn-selector btn-diff-easy active'>😊 Fácil</button>"
    , "          <button onclick=\"selectDifficulty('medium')\" id='btn-medium' class='btn-selector btn-diff-medium'>🤔 Medio</button>"
    , "          <button onclick=\"selectDifficulty('hard')\" id='btn-hard' class='btn-selector btn-diff-hard'>😈 Difícil</button>"
    , "          <button onclick=\"selectDifficulty('extreme')\" id='btn-extreme' class='btn-selector btn-diff-extreme'>🔥 Extremo</button>"
    , "        </div>"
    , "      </div>"
    , ""
    , "      <div class='setup-actions'>"
    , "        <button onclick=\"startGame()\" class='btn-start-game'>🚀 Iniciar Partida</button>"
    , "        <button onclick=\"backToMenu()\" class='btn-back'>⬅️ Volver</button>"
    , "      </div>"
    , "    </div>"
    , "  </div>"
    , ""
    , "  <script>"
    , "    let gameConfig = {"
    , "      gameMode: 'robadito',"
    , "      vsMode: 'freeforall',"
    , "      difficulty: 'easy',"
    , "      dataA100: {"
    , "        enabled: false,"
    , "        targetScore: 100,"
    , "        bonusNoSalida: false,"
    , "        bonusPrimerDoble: false,"
    , "        bonusCapicua: false"
    , "      }"
    , "    };"
    , ""
    , "    function showGameSetup() {"
    , "      document.getElementById('main-menu').classList.add('hidden');"
    , "      document.getElementById('game-setup').classList.remove('hidden');"
    , "    }"
    , ""
    , "    function backToMenu() {"
    , "      document.getElementById('game-setup').classList.add('hidden');"
    , "      document.getElementById('main-menu').classList.remove('hidden');"
    , "    }"
    , ""
    , "    function exitGame() {"
    , "      if (confirm('Seguro que quieres salir?')) {"
    , "        document.body.innerHTML = ''"
    , "          + '<div class=\"exit-screen\">'"
    , "          + '<div class=\"exit-content\">'"
    , "          + '<div class=\"exit-dominos\">🁣 🁩</div>'"
    , "          + '<h1 class=\"exit-title\">Gracias por jugar!</h1>'"
    , "          + '<p class=\"exit-subtitle\">Dominos PizA</p>'"
    , "          + '<p class=\"exit-message\">Puedes cerrar esta pestana o</p>'"
    , "          + '<button onclick=\"location.reload()\" class=\"exit-btn\">Volver a jugar</button>'"
    , "          + '</div>'"
    , "          + '</div>';"
    , "      }"
    , "    }"
    , ""
    , "    function updateData100Visibility() {"
    , "      const section = document.getElementById('data100-section');"
    , "      const show = gameConfig.gameMode === 'norobadito' && gameConfig.vsMode === '2vs2';"
    , "      section.classList.toggle('hidden', !show);"
    , "      if (!show) {"
    , "        gameConfig.dataA100.enabled = false;"
    , "        document.getElementById('data100-enabled').checked = false;"
    , "        document.getElementById('data100-options').classList.add('hidden');"
    , "      }"
    , "    }"
    , ""
    , "    function toggleData100() {"
    , "      const enabled = document.getElementById('data100-enabled').checked;"
    , "      gameConfig.dataA100.enabled = enabled;"
    , "      document.getElementById('data100-options').classList.toggle('hidden', !enabled);"
    , "    }"
    , ""
    , "    function updateData100Target() {"
    , "      gameConfig.dataA100.targetScore = parseInt(document.getElementById('data100-target').value);"
    , "    }"
    , ""
    , "    function updateData100Bonus() {"
    , "      gameConfig.dataA100.bonusNoSalida = document.getElementById('bonus-nosalida').checked;"
    , "      gameConfig.dataA100.bonusPrimerDoble = document.getElementById('bonus-primerdoble').checked;"
    , "      gameConfig.dataA100.bonusCapicua = document.getElementById('bonus-capicua').checked;"
    , "    }"
    , ""
    , "    function selectGameMode(mode) {"
    , "      gameConfig.gameMode = mode;"
    , "      document.getElementById('btn-robadito').classList.toggle('active', mode === 'robadito');"
    , "      document.getElementById('btn-norobadito').classList.toggle('active', mode === 'norobadito');"
    , "      updateData100Visibility();"
    , "    }"
    , ""
    , "    function selectVsMode(mode) {"
    , "      gameConfig.vsMode = mode;"
    , "      document.getElementById('btn-1vs1').classList.toggle('active', mode === '1vs1');"
    , "      document.getElementById('btn-freeforall').classList.toggle('active', mode === 'freeforall');"
    , "      document.getElementById('btn-2vs2').classList.toggle('active', mode === '2vs2');"
    , "      updateData100Visibility();"
    , "    }"
    , ""
    , "    function selectDifficulty(diff) {"
    , "      gameConfig.difficulty = diff;"
    , "      document.getElementById('btn-easy').classList.toggle('active', diff === 'easy');"
    , "      document.getElementById('btn-medium').classList.toggle('active', diff === 'medium');"
    , "      document.getElementById('btn-hard').classList.toggle('active', diff === 'hard');"
    , "      document.getElementById('btn-extreme').classList.toggle('active', diff === 'extreme');"
    , "    }"
    , "    function startGame() {"
    , "      localStorage.setItem('domino-config', JSON.stringify(gameConfig));"
    , "      location.href = '/game';"
    , "    }"
    , "  </script>"
    , "</body>"
    , "</html>"
    ]

-- | Página del juego
gameHtml :: Text
gameHtml = TL.concat
    [ "<!DOCTYPE html>"
    , "<html lang='es'>"
    , "<head>"
    , "  <meta charset='UTF-8'>"
    , "  <meta name='viewport' content='width=device-width, initial-scale=1.0'>"
    , "  <title>Dominó - Partida</title>"
    , "  <style>", cssStyles, "</style>"
    , "</head>"
    , "<body>"
    , "  <div class='game-container'>"
    , "    <header class='game-header'>"
    , "      <div class='mini-title-container'>"
    , "        <div class='mini-domino-piece'>🁣</div>"
    , "        <h1 class='mini-game-title'>"
    , "          <span class='title-domino'>Domino's</span>"
    , "          <span class='title-piza'>PizA</span>"
    , "        </h1>"
    , "        <div class='mini-domino-piece'>🁩</div>"
    , "      </div>"
    , "    </header>"
    , "    "
    , "    <div class='main-layout'>"
    , "      <div class='left-panel'>"
    , "        <div class='board-container'>"
    , "          <div id='board' class='board'></div>"
    , "        </div>"
    , "        "
    , "        <div class='hand-container'>"
    , "          <h3>Tu mano <span id='hand-count'></span></h3>"
    , "          <div id='hand' class='hand'></div>"
    , "        </div>"
    , "      </div>"
    , "      "
    , "      <div class='right-panel'>"
    , "        <div class='info-panel'>"
    , "          <h3>Jugadores</h3>"
    , "          <div id='players'></div>"
    , "        </div>"
    , "        <div class='message-panel'>"
    , "          <h3>Estado</h3>"
    , "          <div id='message' class='message'></div>"
    , "        </div>"
    , "        <div class='actions-panel'>"
    , "          <h3>Acciones</h3>"
    , "          <button id='btn-draw' class='btn btn-action' onclick='drawTile()'>🎴 Robar</button>"
    , "          <button id='btn-pass' class='btn btn-action' onclick='passTurn()'>⏭️ Pasar</button>"
    , "          <button class='btn btn-new' onclick='newGame()'>🔄 Nueva Partida</button>"
    , "          <button class='btn btn-menu' onclick='goToMenu()'>🏠 Menú</button>"
    , "        </div>"
    , "      </div>"
    , "    </div>"
    , "    "
    , "    <div id='side-selector' class='side-selector hidden'>"
    , "      <p>¿En qué lado quieres jugar?</p>"
    , "      <button class='btn' onclick='playSelected(\"left\")'>⬅️ Izquierda</button>"
    , "      <button class='btn' onclick='playSelected(\"right\")'>➡️ Derecha</button>"
    , "      <button class='btn btn-cancel' onclick='cancelSelection()'>Cancelar</button>"
    , "    </div>"
    , "  </div>"
    , "  "
    , "  <div id='game-over-modal' class='modal hidden'>"
    , "    <div class='modal-content'>"
    , "      <h2>🎉 ¡Ronda Terminada!</h2>"
    , "      <div id='win-details' class='win-details'></div>"
    , "      <p id='winner-text' class='winner-text'></p>"
    , "      <div id='match-score-summary' class='match-score-summary hidden'></div>"
    , "      <div class='modal-buttons'>"
    , "        <button id='btn-next-round-modal' class='btn btn-continue hidden' onclick='nextRound()'>▶️ Siguiente Ronda</button>"
    , "        <button id='btn-new-game-modal' class='btn btn-new' onclick='newGame()'>🔄 Nueva Partida</button>"
    , "        <button class='btn btn-menu' onclick='goToMenu()'>🏠 Menú</button>"
    , "      </div>"
    , "    </div>"
    , "  </div>"
    , "  "
    , "  <script>", jsScript, "</script>"
    , "</body>"
    , "</html>"
    ]

-- | Estilos CSS
cssStyles :: Text
cssStyles = TL.concat
    [ "* { box-sizing: border-box; margin: 0; padding: 0; }"
    , "body { "
    , "  font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;"
    , "  background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);"
    , "  min-height: 100vh;"
    , "  color: #fff;"
    , "}"
    , ".container {"
    , "  display: flex;"
    , "  flex-direction: column;"
    , "  align-items: center;"
    , "  justify-content: center;"
    , "  min-height: 100vh;"
    , "  text-align: center;"
    , "}"
    , ".container h1 { font-size: 4rem; margin-bottom: 1rem; }"
    , ".container p { font-size: 1.2rem; margin-bottom: 2rem; color: #aaa; }"
    , ".btn-start {"
    , "  padding: 1rem 3rem;"
    , "  font-size: 1.5rem;"
    , "  background: linear-gradient(45deg, #e94560, #ff6b6b);"
    , "  border: none;"
    , "  border-radius: 50px;"
    , "  color: white;"
    , "  cursor: pointer;"
    , "  transition: transform 0.3s, box-shadow 0.3s;"
    , "}"
    , ".btn-start:hover {"
    , "  transform: scale(1.05);"
    , "  box-shadow: 0 10px 30px rgba(233, 69, 96, 0.4);"
    , "}"
    , ".game-container {"
    , "  max-width: 1600px;"
    , "  margin: 0 auto;"
    , "  padding: 0.3rem;"
    , "  height: 100vh;"
    , "  display: flex;"
    , "  flex-direction: column;"
    , "}"
    , ".game-header {"
    , "  text-align: center;"
    , "  padding: 0.3rem;"
    , "  flex-shrink: 0;"
    , "}"
    , ".mini-title-container {"
    , "  display: flex;"
    , "  justify-content: center;"
    , "  align-items: center;"
    , "  gap: 0.8rem;"
    , "}"
    , ".mini-domino-piece {"
    , "  font-size: 2rem;"
    , "  animation: rotate 3s ease-in-out infinite;"
    , "  filter: drop-shadow(0 0 10px rgba(255,215,0,0.5));"
    , "}"
    , ".mini-game-title {"
    , "  font-size: 1.8rem;"
    , "  font-family: Georgia, serif;"
    , "  margin: 0;"
    , "}"
    , ".title-domino {"
    , "  background: linear-gradient(45deg, #ffd700, #ff8c00);"
    , "  -webkit-background-clip: text;"
    , "  -webkit-text-fill-color: transparent;"
    , "  background-clip: text;"
    , "}"
    , ".title-piza {"
    , "  background: linear-gradient(45deg, #00bcd4, #4dd0e1);"
    , "  -webkit-background-clip: text;"
    , "  -webkit-text-fill-color: transparent;"
    , "  background-clip: text;"
    , "  font-style: italic;"
    , "}"
    , "@keyframes rotate {"
    , "  0%, 100% { transform: rotate(-10deg); }"
    , "  50% { transform: rotate(10deg); }"
    , "}"
    , ".main-layout {"
    , "  display: flex;"
    , "  gap: 0.5rem;"
    , "  align-items: flex-start;"
    , "  flex: 1;"
    , "  min-height: 0;"
    , "}"
    , ".left-panel {"
    , "  flex: 1;"
    , "  min-width: 0;"
    , "  display: flex;"
    , "  flex-direction: column;"
    , "  height: 100%;"
    , "}"
    , ".right-panel {"
    , "  width: 220px;"
    , "  flex-shrink: 0;"
    , "  display: flex;"
    , "  flex-direction: column;"
    , "  gap: 1rem;"
    , "}"
    , ".info-panel, .message-panel, .actions-panel {"
    , "  background: rgba(255,255,255,0.08);"
    , "  border-radius: 15px;"
    , "  padding: 1rem;"
    , "  border: 2px solid rgba(255,255,255,0.1);"
    , "}"
    , ".info-panel h3, .message-panel h3, .actions-panel h3 {"
    , "  margin: 0 0 0.8rem 0;"
    , "  font-size: 1.1rem;"
    , "  color: #e94560;"
    , "  text-align: center;"
    , "}"
    , ".actions-panel {"
    , "  display: flex;"
    , "  flex-direction: column;"
    , "  gap: 0.5rem;"
    , "}"
    , ".actions-panel .btn {"
    , "  width: 100%;"
    , "  padding: 0.6rem;"
    , "  font-size: 0.9rem;"
    , "}"
    , ".message {"
    , "  background: rgba(255,255,255,0.1);"
    , "  padding: 0.8rem;"
    , "  border-radius: 10px;"
    , "  font-size: 0.95rem;"
    , "  min-height: 40px;"
    , "  text-align: center;"
    , "}"
    , ".players-info {"
    , "  display: flex;"
    , "  flex-direction: column;"
    , "  gap: 0.5rem;"
    , "}"
    , ".player-card {"
    , "  background: rgba(255,255,255,0.1);"
    , "  padding: 0.5rem 0.8rem;"
    , "  border-radius: 8px;"
    , "  text-align: center;"
    , "  margin-bottom: 0.3rem;"
    , "}"
    , ".player-card.active {"
    , "  background: linear-gradient(45deg, #e94560, #ff6b6b);"
    , "  box-shadow: 0 3px 10px rgba(233, 69, 96, 0.4);"
    , "}"
    , ".player-card .name { font-weight: bold; font-size: 0.9rem; }"
    , ".player-card .count { font-size: 0.8rem; opacity: 0.8; }"
    , "/* Estilos para equipos en modo 2vs2 */"
    , ".team-container {"
    , "  display: flex;"
    , "  flex-direction: column;"
    , "  gap: 0.3rem;"
    , "  padding: 0.5rem;"
    , "  border-radius: 10px;"
    , "  margin-bottom: 0.5rem;"
    , "}"
    , ".team-a { background: rgba(46, 204, 113, 0.2); border: 2px solid #2ecc71; }"
    , ".team-b { background: rgba(231, 76, 60, 0.2); border: 2px solid #e74c3c; }"
    , ".team-label {"
    , "  font-weight: bold;"
    , "  font-size: 0.85rem;"
    , "  padding: 0.4rem 0.8rem;"
    , "  border-radius: 8px;"
    , "  white-space: nowrap;"
    , "}"
    , ".team-a-player.active { background: linear-gradient(45deg, #27ae60, #2ecc71) !important; }"
    , ".team-b-player.active { background: linear-gradient(45deg, #c0392b, #e74c3c) !important; }"
    , ".board-container {"
    , "  background: linear-gradient(145deg, #2d5016, #1a3009);"
    , "  border-radius: 15px;"
    , "  padding: 0.5rem;"
    , "  margin: 0.3rem 0;"
    , "  flex: 1;"
    , "  min-height: 0;"
    , "  box-shadow: inset 0 8px 30px rgba(0,0,0,0.4), 0 10px 40px rgba(0,0,0,0.3);"
    , "  border: 3px solid #3d6620;"
    , "  overflow: hidden;"
    , "}"
    , ".board-container h3 {"
    , "  text-align: center;"
    , "  margin: 0.3rem 0;"
    , "  color: #90EE90;"
    , "  font-size: 1rem;"
    , "}"
    , ".board {"
    , "  position: relative;"
    , "  width: 100%;"
    , "  height: calc(100% - 30px);"
    , "}"
    , ".board-tile {"
    , "  position: absolute;"
    , "  transition: none;"
    , "}"
    , ".hand-container {"
    , "  background: rgba(255,255,255,0.08);"
    , "  border-radius: 10px;"
    , "  padding: 0.5rem;"
    , "  margin: 0.3rem 0;"
    , "  border: 2px solid rgba(255,255,255,0.1);"
    , "  flex-shrink: 0;"
    , "}"
    , ".hand-container h3 {"
    , "  text-align: center;"
    , "  margin-bottom: 0.4rem;"
    , "  font-size: 1rem;"
    , "}"
    , ".hand {"
    , "  display: flex;"
    , "  flex-wrap: wrap;"
    , "  justify-content: center;"
    , "  gap: 8px;"
    , "}"
    , ".domino {"
    , "  background: linear-gradient(145deg, #fff, #e0e0e0);"
    , "  border-radius: 10px;"
    , "  display: flex;"
    , "  box-shadow: 3px 3px 12px rgba(0,0,0,0.4);"
    , "  cursor: pointer;"
    , "  transition: transform 0.2s, box-shadow 0.2s;"
    , "}"
    , ".domino:hover {"
    , "  transform: translateY(-8px);"
    , "  box-shadow: 6px 12px 24px rgba(0,0,0,0.5);"
    , "}"
    , ".domino.selected {"
    , "  box-shadow: 0 0 30px #00ff00;"
    , "  transform: translateY(-12px);"
    , "}"
    , ".domino.horizontal {"
    , "  flex-direction: row;"
    , "  width: 100px;"
    , "  height: 50px;"
    , "}"
    , ".domino.vertical {"
    , "  flex-direction: column;"
    , "  width: 50px;"
    , "  height: 100px;"
    , "}"
    , ".domino-half {"
    , "  flex: 1;"
    , "  display: flex;"
    , "  justify-content: center;"
    , "  align-items: center;"
    , "  font-weight: bold;"
    , "  color: #333;"
    , "  font-size: 18px;"
    , "  position: relative;"
    , "}"
    , ".domino.horizontal .domino-half {"
    , "  border-right: 2px solid #999;"
    , "}"
    , ".domino.horizontal .domino-half:last-child {"
    , "  border-right: none;"
    , "}"
    , ".domino.vertical .domino-half {"
    , "  border-bottom: 2px solid #999;"
    , "}"
    , ".domino.vertical .domino-half:last-child {"
    , "  border-bottom: none;"
    , "}"
    , ".domino.board-tile {"
    , "  cursor: default;"
    , "  transform: none;"
    , "}"
    , ".domino.board-tile:hover {"
    , "  transform: none;"
    , "}"
    , ".domino.double {"
    , "  flex-direction: column;"
    , "  width: 35px;"
    , "  height: 70px;"
    , "}"
    , ".btn {"
    , "  padding: 0.6rem 1.2rem;"
    , "  font-size: 0.9rem;"
    , "  background: rgba(255,255,255,0.1);"
    , "  border: 1px solid rgba(255,255,255,0.2);"
    , "  border-radius: 10px;"
    , "  color: white;"
    , "  cursor: pointer;"
    , "  transition: all 0.3s;"
    , "}"
    , ".btn:hover {"
    , "  background: rgba(255,255,255,0.2);"
    , "}"
    , ".btn:disabled {"
    , "  opacity: 0.5;"
    , "  cursor: not-allowed;"
    , "}"
    , ".btn-new {"
    , "  background: linear-gradient(45deg, #e94560, #ff6b6b);"
    , "  border: none;"
    , "}"
    , ".btn-menu {"
    , "  background: linear-gradient(45deg, #2196F3, #03A9F4);"
    , "  border: none;"
    , "}"
    , ".btn-cancel {"
    , "  background: rgba(255,0,0,0.3);"
    , "}"
    , ".side-selector {"
    , "  position: fixed;"
    , "  bottom: 20px;"
    , "  left: 50%;"
    , "  transform: translateX(-50%);"
    , "  background: rgba(0,0,0,0.9);"
    , "  padding: 1rem 2rem;"
    , "  border-radius: 15px;"
    , "  text-align: center;"
    , "  z-index: 100;"
    , "  box-shadow: 0 10px 40px rgba(0,0,0,0.5);"
    , "}"
    , ".side-selector p { margin-bottom: 1rem; }"
    , ".hidden { display: none !important; }"
    , ".modal {"
    , "  position: fixed;"
    , "  top: 0;"
    , "  left: 0;"
    , "  width: 100%;"
    , "  height: 100%;"
    , "  background: rgba(0,0,0,0.8);"
    , "  display: flex;"
    , "  justify-content: center;"
    , "  align-items: center;"
    , "  z-index: 1000;"
    , "}"
    , ".modal-content {"
    , "  background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);"
    , "  padding: 3rem;"
    , "  border-radius: 20px;"
    , "  text-align: center;"
    , "  box-shadow: 0 20px 60px rgba(0,0,0,0.5);"
    , "  min-width: 350px;"
    , "}"
    , ".modal-content h2 { font-size: 2rem; margin-bottom: 1rem; }"
    , ".modal-content p { margin-bottom: 1rem; font-size: 1.2rem; }"
    , ".win-details {"
    , "  background: rgba(255,255,255,0.1);"
    , "  padding: 1rem;"
    , "  border-radius: 10px;"
    , "  margin-bottom: 1rem;"
    , "  font-size: 1rem;"
    , "  line-height: 1.6;"
    , "}"
    , ".win-details.hidden { display: none; }"
    , ".winner-text {"
    , "  font-size: 1.3rem;"
    , "  font-weight: bold;"
    , "  color: #ffd700;"
    , "  margin-bottom: 1rem;"
    , "}"
    , ".modal-buttons {"
    , "  display: flex;"
    , "  flex-direction: column;"
    , "  gap: 0.8rem;"
    , "  margin-top: 1.5rem;"
    , "}"
    , ".modal-buttons .btn {"
    , "  padding: 1rem 2rem;"
    , "  font-size: 1.1rem;"
    , "  border: none;"
    , "  border-radius: 10px;"
    , "  cursor: pointer;"
    , "  transition: all 0.3s;"
    , "  font-weight: bold;"
    , "}"
    , ".btn-continue {"
    , "  background: linear-gradient(45deg, #FFC107, #FF9800);"
    , "  color: #000;"
    , "}"
    , ".btn-continue:hover {"
    , "  transform: scale(1.03);"
    , "  box-shadow: 0 5px 20px rgba(255,193,7,0.4);"
    , "}"
    , ".btn-new {"
    , "  background: linear-gradient(45deg, #4CAF50, #8BC34A);"
    , "  color: white;"
    , "}"
    , ".btn-new:hover {"
    , "  transform: scale(1.03);"
    , "  box-shadow: 0 5px 20px rgba(76,175,80,0.4);"
    , "}"
    , ".btn-menu {"
    , "  background: rgba(255,255,255,0.1);"
    , "  color: white;"
    , "  border: 1px solid rgba(255,255,255,0.2);"
    , "}"
    , ".btn-menu:hover {"
    , "  background: rgba(255,255,255,0.2);"
    , "}"
    , ".match-score-summary {"
    , "  background: rgba(0,0,0,0.3);"
    , "  border-radius: 10px;"
    , "  padding: 1rem;"
    , "  margin: 1rem 0;"
    , "}"
    , ".match-score-summary .scores {"
    , "  display: flex;"
    , "  justify-content: space-around;"
    , "  font-size: 1.3rem;"
    , "  margin-bottom: 0.5rem;"
    , "}"
    , ".match-score-summary .team-a { color: #4CAF50; }"
    , ".match-score-summary .team-b { color: #f44336; }"
    , ".match-score-summary .target {"
    , "  font-size: 0.9rem;"
    , "  opacity: 0.7;"
    , "}"
    , ".match-winner-text {"
    , "  color: #FFC107;"
    , "  font-size: 1.5rem;"
    , "  font-weight: bold;"
    , "  margin-top: 0.5rem;"
    , "}"
    , ".exit-screen {"
    , "  position: fixed;"
    , "  top: 0;"
    , "  left: 0;"
    , "  width: 100%;"
    , "  height: 100%;"
    , "  background: linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%);"
    , "  display: flex;"
    , "  justify-content: center;"
    , "  align-items: center;"
    , "}"
    , ".exit-content {"
    , "  text-align: center;"
    , "  animation: fadeIn 0.5s ease-out;"
    , "}"
    , "@keyframes fadeIn {"
    , "  from { opacity: 0; transform: scale(0.8); }"
    , "  to { opacity: 1; transform: scale(1); }"
    , "}"
    , ".exit-dominos {"
    , "  font-size: 6rem;"
    , "  margin-bottom: 2rem;"
    , "  animation: float 3s ease-in-out infinite;"
    , "}"
    , "@keyframes float {"
    , "  0%, 100% { transform: translateY(0); }"
    , "  50% { transform: translateY(-20px); }"
    , "}"
    , ".exit-title {"
    , "  font-size: 3.5rem;"
    , "  color: #fff;"
    , "  margin-bottom: 1rem;"
    , "  background: linear-gradient(45deg, #FFD700, #FFA500);"
    , "  -webkit-background-clip: text;"
    , "  -webkit-text-fill-color: transparent;"
    , "  background-clip: text;"
    , "}"
    , ".exit-subtitle {"
    , "  font-size: 1.8rem;"
    , "  color: #00CED1;"
    , "  margin-bottom: 2rem;"
    , "  font-style: italic;"
    , "}"
    , ".exit-message {"
    , "  font-size: 1.2rem;"
    , "  color: #aaa;"
    , "  margin-bottom: 1.5rem;"
    , "}"
    , ".exit-btn {"
    , "  padding: 1rem 3rem;"
    , "  font-size: 1.3rem;"
    , "  background: linear-gradient(45deg, #4CAF50, #8BC34A);"
    , "  border: none;"
    , "  border-radius: 50px;"
    , "  color: white;"
    , "  cursor: pointer;"
    , "  transition: transform 0.3s, box-shadow 0.3s;"
    , "  font-weight: bold;"
    , "}"
    , ".exit-btn:hover {"
    , "  transform: scale(1.1);"
    , "  box-shadow: 0 10px 40px rgba(76, 175, 80, 0.5);"
    , "}"
    , ".pip {"
    , "  width: 8px;"
    , "  height: 8px;"
    , "  background: #333;"
    , "  border-radius: 50%;"
    , "  position: absolute;"
    , "}"
    ]

-- | Estilos adicionales para la página de inicio
indexCssStyles :: Text
indexCssStyles = TL.concat
    [ "@keyframes bounce {"
    , "  0%, 100% { transform: translateY(0); }"
    , "  50% { transform: translateY(-15px); }"
    , "}"
    , "@keyframes glow {"
    , "  0%, 100% { text-shadow: 0 0 10px #ff6b6b, 0 0 20px #ff6b6b, 0 0 30px #ff6b6b; }"
    , "  50% { text-shadow: 0 0 20px #ffd700, 0 0 40px #ffd700, 0 0 60px #ffd700; }"
    , "}"
    , "@keyframes rotate {"
    , "  0% { transform: rotate(-10deg); }"
    , "  50% { transform: rotate(10deg); }"
    , "  100% { transform: rotate(-10deg); }"
    , "}"
    , ".title-container {"
    , "  display: flex;"
    , "  align-items: center;"
    , "  justify-content: center;"
    , "  gap: 1rem;"
    , "  margin-bottom: 1rem;"
    , "}"
    , ".domino-piece {"
    , "  font-size: 4rem;"
    , "  animation: rotate 2s ease-in-out infinite;"
    , "  filter: drop-shadow(0 0 10px rgba(255,255,255,0.5));"
    , "}"
    , ".game-title {"
    , "  font-size: 3.5rem;"
    , "  font-family: 'Georgia', serif;"
    , "  letter-spacing: 3px;"
    , "  margin: 0;"
    , "}"
    , ".title-domino {"
    , "  background: linear-gradient(45deg, #FFD700, #FFA500, #FF6347);"
    , "  -webkit-background-clip: text;"
    , "  -webkit-text-fill-color: transparent;"
    , "  background-clip: text;"
    , "  font-weight: bold;"
    , "  text-shadow: none;"
    , "  filter: drop-shadow(2px 2px 4px rgba(0,0,0,0.5));"
    , "}"
    , ".title-piza {"
    , "  background: linear-gradient(45deg, #00CED1, #20B2AA, #48D1CC);"
    , "  -webkit-background-clip: text;"
    , "  -webkit-text-fill-color: transparent;"
    , "  background-clip: text;"
    , "  font-style: italic;"
    , "  font-weight: bold;"
    , "  filter: drop-shadow(2px 2px 4px rgba(0,0,0,0.5));"
    , "}"
    , ".bouncy-text {"
    , "  font-size: 1.3rem;"
    , "  color: #90EE90;"
    , "  margin: 1.5rem 0;"
    , "}"
    , ".bouncy-text span {"
    , "  display: inline-block;"
    , "  animation: bounce 2s ease-in-out infinite;"
    , "}"
    , ".menu-buttons {"
    , "  display: flex;"
    , "  gap: 2rem;"
    , "  margin-top: 3rem;"
    , "}"
    , ".btn-start {"
    , "  padding: 1.5rem 3rem;"
    , "  font-size: 1.5rem;"
    , "  background: linear-gradient(45deg, #4CAF50, #8BC34A);"
    , "  border: none;"
    , "  border-radius: 15px;"
    , "  color: white;"
    , "  cursor: pointer;"
    , "  transition: transform 0.3s, box-shadow 0.3s;"
    , "  font-weight: bold;"
    , "}"
    , ".btn-start:hover {"
    , "  transform: scale(1.05);"
    , "  box-shadow: 0 10px 30px rgba(76, 175, 80, 0.5);"
    , "}"
    , ".btn-exit {"
    , "  padding: 1.5rem 3rem;"
    , "  font-size: 1.5rem;"
    , "  background: linear-gradient(45deg, #f44336, #E91E63);"
    , "  border: none;"
    , "  border-radius: 15px;"
    , "  color: white;"
    , "  cursor: pointer;"
    , "  transition: transform 0.3s, box-shadow 0.3s;"
    , "  font-weight: bold;"
    , "}"
    , ".btn-exit:hover {"
    , "  transform: scale(1.05);"
    , "  box-shadow: 0 10px 30px rgba(244, 67, 54, 0.5);"
    , "}"
    , ".setup-container {"
    , "  background: rgba(255,255,255,0.05);"
    , "  border-radius: 20px;"
    , "  padding: 2rem;"
    , "  max-width: 600px;"
    , "  margin: 0 auto;"
    , "}"
    , ".setup-section {"
    , "  margin-bottom: 2rem;"
    , "}"
    , ".setup-section h3 {"
    , "  margin-bottom: 1rem;"
    , "  color: #90EE90;"
    , "}"
    , ".selector-group {"
    , "  display: flex;"
    , "  gap: 1rem;"
    , "  flex-wrap: wrap;"
    , "  justify-content: center;"
    , "}"
    , ".btn-selector {"
    , "  padding: 1rem 1.5rem;"
    , "  font-size: 1.1rem;"
    , "  background: rgba(255,255,255,0.1);"
    , "  border: 2px solid rgba(255,255,255,0.2);"
    , "  border-radius: 10px;"
    , "  color: white;"
    , "  cursor: pointer;"
    , "  transition: all 0.3s;"
    , "}"
    , ".btn-selector:hover:not(.disabled) {"
    , "  background: rgba(255,255,255,0.2);"
    , "  transform: translateY(-3px);"
    , "}"
    , ".btn-selector.active {"
    , "  background: linear-gradient(45deg, #e94560, #ff6b6b);"
    , "  border-color: #ff6b6b;"
    , "  box-shadow: 0 5px 20px rgba(233, 69, 96, 0.4);"
    , "}"
    , ".btn-selector.disabled {"
    , "  opacity: 0.4;"
    , "  cursor: not-allowed;"
    , "}"
    , ".btn-diff-easy.active {"
    , "  background: linear-gradient(45deg, #4CAF50, #8BC34A);"
    , "  border-color: #8BC34A;"
    , "  box-shadow: 0 5px 20px rgba(76, 175, 80, 0.4);"
    , "}"
    , ".btn-diff-medium.active {"
    , "  background: linear-gradient(45deg, #FF9800, #FFC107);"
    , "  border-color: #FFC107;"
    , "  box-shadow: 0 5px 20px rgba(255, 152, 0, 0.4);"
    , "}"
    , ".btn-diff-hard.active {"
    , "  background: linear-gradient(45deg, #f44336, #E91E63);"
    , "  border-color: #E91E63;"
    , "  box-shadow: 0 5px 20px rgba(244, 67, 54, 0.4);"
    , "}"
    , ".btn-diff-extreme.active {"
    , "  background: linear-gradient(45deg, #9C27B0, #673AB7);"
    , "  border-color: #673AB7;"
    , "  box-shadow: 0 5px 20px rgba(156, 39, 176, 0.5), 0 0 30px rgba(103, 58, 183, 0.3);"
    , "  animation: extremePulse 1.5s ease-in-out infinite;"
    , "}"
    , "@keyframes extremePulse {"
    , "  0%, 100% { box-shadow: 0 5px 20px rgba(156, 39, 176, 0.5); }"
    , "  50% { box-shadow: 0 5px 30px rgba(156, 39, 176, 0.8), 0 0 40px rgba(103, 58, 183, 0.5); }"
    , "}"
    , ""
    , "/* Data a 100 Styles */"
    , ".data100-section {"
    , "  background: linear-gradient(135deg, rgba(255,193,7,0.1), rgba(255,152,0,0.1));"
    , "  border: 2px solid rgba(255,193,7,0.3);"
    , "  border-radius: 15px;"
    , "  padding: 1.5rem;"
    , "}"
    , ".data100-toggle {"
    , "  display: flex;"
    , "  align-items: center;"
    , "  gap: 1rem;"
    , "  margin-bottom: 1rem;"
    , "}"
    , ".toggle-switch {"
    , "  position: relative;"
    , "  width: 60px;"
    , "  height: 30px;"
    , "}"
    , ".toggle-switch input {"
    , "  opacity: 0;"
    , "  width: 0;"
    , "  height: 0;"
    , "}"
    , ".toggle-slider {"
    , "  position: absolute;"
    , "  cursor: pointer;"
    , "  top: 0; left: 0; right: 0; bottom: 0;"
    , "  background: rgba(255,255,255,0.2);"
    , "  border-radius: 30px;"
    , "  transition: 0.3s;"
    , "}"
    , ".toggle-slider:before {"
    , "  position: absolute;"
    , "  content: '';"
    , "  height: 22px;"
    , "  width: 22px;"
    , "  left: 4px;"
    , "  bottom: 4px;"
    , "  background: white;"
    , "  border-radius: 50%;"
    , "  transition: 0.3s;"
    , "}"
    , ".toggle-switch input:checked + .toggle-slider {"
    , "  background: linear-gradient(45deg, #FFC107, #FF9800);"
    , "}"
    , ".toggle-switch input:checked + .toggle-slider:before {"
    , "  transform: translateX(30px);"
    , "}"
    , ".data100-options {"
    , "  margin-top: 1rem;"
    , "  padding-top: 1rem;"
    , "  border-top: 1px solid rgba(255,255,255,0.1);"
    , "}"
    , ".data100-target {"
    , "  display: flex;"
    , "  align-items: center;"
    , "  gap: 1rem;"
    , "  margin-bottom: 1rem;"
    , "}"
    , ".data100-target select {"
    , "  padding: 0.5rem 1rem;"
    , "  border-radius: 8px;"
    , "  background: rgba(255,255,255,0.1);"
    , "  border: 1px solid rgba(255,255,255,0.2);"
    , "  color: white;"
    , "  font-size: 1rem;"
    , "}"
    , ".bonus-options {"
    , "  display: flex;"
    , "  flex-direction: column;"
    , "  gap: 0.8rem;"
    , "}"
    , ".bonus-option {"
    , "  display: flex;"
    , "  align-items: center;"
    , "  gap: 0.5rem;"
    , "  cursor: pointer;"
    , "  padding: 0.5rem;"
    , "  border-radius: 8px;"
    , "  transition: background 0.2s;"
    , "}"
    , ".bonus-option:hover {"
    , "  background: rgba(255,255,255,0.05);"
    , "}"
    , ".bonus-option input[type='checkbox'] {"
    , "  width: 20px;"
    , "  height: 20px;"
    , "  accent-color: #FFC107;"
    , "}"
    , ""
    , "/* Match Score Display */"
    , ".match-score-panel {"
    , "  position: fixed;"
    , "  top: 10px;"
    , "  right: 10px;"
    , "  background: linear-gradient(135deg, rgba(0,0,0,0.8), rgba(30,30,30,0.9));"
    , "  border: 2px solid #FFC107;"
    , "  border-radius: 15px;"
    , "  padding: 1rem;"
    , "  min-width: 200px;"
    , "  z-index: 1000;"
    , "}"
    , ".match-score-panel h3 {"
    , "  margin: 0 0 0.5rem 0;"
    , "  color: #FFC107;"
    , "  font-size: 1rem;"
    , "  text-align: center;"
    , "}"
    , ".match-scores {"
    , "  display: flex;"
    , "  justify-content: space-around;"
    , "  margin-bottom: 0.5rem;"
    , "}"
    , ".team-score {"
    , "  text-align: center;"
    , "}"
    , ".team-score .label {"
    , "  font-size: 0.8rem;"
    , "  opacity: 0.7;"
    , "}"
    , ".team-score .score {"
    , "  font-size: 1.5rem;"
    , "  font-weight: bold;"
    , "}"
    , ".team-score.team-a .score { color: #4CAF50; }"
    , ".team-score.team-b .score { color: #f44336; }"
    , ".match-target {"
    , "  text-align: center;"
    , "  font-size: 0.8rem;"
    , "  opacity: 0.6;"
    , "  border-top: 1px solid rgba(255,255,255,0.1);"
    , "  padding-top: 0.5rem;"
    , "}"
    , ".match-round {"
    , "  text-align: center;"
    , "  font-size: 0.9rem;"
    , "  color: #FFC107;"
    , "  margin-bottom: 0.5rem;"
    , "}"
    , ".btn-next-round {"
    , "  width: 100%;"
    , "  padding: 0.8rem;"
    , "  margin-top: 0.5rem;"
    , "  background: linear-gradient(45deg, #FFC107, #FF9800);"
    , "  border: none;"
    , "  border-radius: 8px;"
    , "  color: #000;"
    , "  font-weight: bold;"
    , "  cursor: pointer;"
    , "  transition: transform 0.2s;"
    , "}"
    , ".btn-next-round:hover {"
    , "  transform: scale(1.02);"
    , "}"
    , ""
    , ".setup-actions {"
    , "  display: flex;"
    , "  gap: 1rem;"
    , "  justify-content: center;"
    , "  margin-top: 2rem;"
    , "}"
    , ".btn-start-game {"
    , "  padding: 1rem 2rem;"
    , "  font-size: 1.3rem;"
    , "  background: linear-gradient(45deg, #4CAF50, #8BC34A);"
    , "  border: none;"
    , "  border-radius: 10px;"
    , "  color: white;"
    , "  cursor: pointer;"
    , "  transition: all 0.3s;"
    , "  font-weight: bold;"
    , "}"
    , ".btn-start-game:hover {"
    , "  transform: scale(1.05);"
    , "  box-shadow: 0 10px 30px rgba(76, 175, 80, 0.5);"
    , "}"
    , ".btn-back {"
    , "  padding: 1rem 2rem;"
    , "  font-size: 1.3rem;"
    , "  background: rgba(255,255,255,0.1);"
    , "  border: 2px solid rgba(255,255,255,0.2);"
    , "  border-radius: 10px;"
    , "  color: white;"
    , "  cursor: pointer;"
    , "  transition: all 0.3s;"
    , "}"
    , ".btn-back:hover {"
    , "  background: rgba(255,255,255,0.2);"
    , "}"
    , ".difficulty-selector {"
    , "  margin-top: 3rem;"
    , "  display: flex;"
    , "  flex-direction: column;"
    , "  align-items: center;"
    , "  gap: 2rem;"
    , "}"
    , ".difficulty-selector h2 {"
    , "  font-size: 1.8rem;"
    , "  margin-bottom: 0;"
    , "}"
    , ".difficulty-buttons {"
    , "  display: flex;"
    , "  gap: 2rem;"
    , "  flex-wrap: wrap;"
    , "  justify-content: center;"
    , "}"
    , ".btn-difficulty {"
    , "  padding: 1.5rem 3rem;"
    , "  font-size: 1.5rem;"
    , "  border: none;"
    , "  border-radius: 15px;"
    , "  color: white;"
    , "  cursor: pointer;"
    , "  transition: transform 0.3s, box-shadow 0.3s;"
    , "  font-weight: bold;"
    , "  min-width: 200px;"
    , "}"
    , ".btn-easy {"
    , "  background: linear-gradient(45deg, #4CAF50, #8BC34A);"
    , "}"
    , ".btn-easy:hover {"
    , "  transform: scale(1.05);"
    , "  box-shadow: 0 10px 30px rgba(76, 175, 80, 0.5);"
    , "}"
    , ".btn-medium {"
    , "  background: linear-gradient(45deg, #FF9800, #FFC107);"
    , "}"
    , ".btn-medium:hover {"
    , "  transform: scale(1.05);"
    , "  box-shadow: 0 10px 30px rgba(255, 152, 0, 0.5);"
    , "}"
    , ".btn-hard {"
    , "  background: linear-gradient(45deg, #f44336, #E91E63);"
    , "}"
    , ".btn-hard:hover {"
    , "  transform: scale(1.05);"
    , "  box-shadow: 0 10px 30px rgba(244, 67, 54, 0.5);"
    , "}"
    ]

-- | JavaScript del juego
jsScript :: Text
jsScript = TL.unlines
    [ "let gameState = null;"
    , "let selectedDomino = null;"
    , "let controlled = '0'; // '0','1','2','3' or 'all'"
    , "function onControlChange(v) { controlled = v; render(); }"
    , ""
    , "async function fetchState() {"
    , "  const res = await fetch('/api/state');"
    , "  gameState = await res.json();"
    , "  console.log('Estado recibido:', gameState);"
    , "  console.log('Mano jugador 0:', gameState.grPlayers[0].pjHand);"
    , "  render();"
    , "}"
    , ""
    , "async function newGame() {"
    , "  const configStr = localStorage.getItem('domino-config');"
    , "  let config = { gameMode: 'robadito', vsMode: 'freeforall', difficulty: 'easy' };"
    , "  if (configStr) {"
    , "    try { config = JSON.parse(configStr); } catch(e) {}"
    , "  }"
    , "  const res = await fetch('/api/new', { "
    , "    method: 'POST',"
    , "    headers: { 'Content-Type': 'application/json' },"
    , "    body: JSON.stringify(config)"
    , "  });"
    , "  gameState = await res.json();"
    , "  selectedDomino = null;"
    , "  document.getElementById('game-over-modal').classList.add('hidden');"
    , "  render();"
    , "}"
    , ""
    , "async function playTile(domino, side) {"
    , "  const res = await fetch('/api/play', {"
    , "    method: 'POST',"
    , "    headers: { 'Content-Type': 'application/json' },"
    , "    body: JSON.stringify({ action: 'play', domino: domino, side: side })"
    , "  });"
    , "  gameState = await res.json();"
    , "  selectedDomino = null;"
    , "  render();"
    , "}"
    , ""
    , "async function drawTile() {"
    , "  const res = await fetch('/api/play', {"
    , "    method: 'POST',"
    , "    headers: { 'Content-Type': 'application/json' },"
    , "    body: JSON.stringify({ action: 'draw', domino: null, side: null })"
    , "  });"
    , "  gameState = await res.json();"
    , "  render();"
    , "}"
    , ""
    , "async function passTurn() {"
    , "  const res = await fetch('/api/play', {"
    , "    method: 'POST',"
    , "    headers: { 'Content-Type': 'application/json' },"
    , "    body: JSON.stringify({ action: 'pass', domino: null, side: null })"
    , "  });"
    , "  gameState = await res.json();"
    , "  render();"
    , "}"
    , ""
    , "function isControlledTurn() { return controlled === 'all' || (parseInt(controlled) === gameState.grCurrentPlayer); }"
    , "function selectDomino(domino) {"
    , "  if (gameState.grGameOver) return;"
    , "  if (!isControlledTurn()) {"
    , "    alert('No es tu turno (control seleccionado). Cambia el control para jugar este jugador.');"
    , "    return;"
    , "  }"
    , "  selectedDomino = domino;"
    , "  "
    , "  // Si el tablero está vacío, jugar automáticamente"
    , "  if (gameState.grBoard.bjTiles.length === 0) {"
    , "    playTile(domino, 'right');"
    , "    return;"
    , "  }"
    , "  "
    , "  // Mostrar selector de lado"
    , "  document.getElementById('side-selector').classList.remove('hidden');"
    , "  render();"
    , "}"
    , ""
    , "function playSelected(side) {"
    , "  if (selectedDomino) {"
    , "    playTile(selectedDomino, side);"
    , "  }"
    , "  document.getElementById('side-selector').classList.add('hidden');"
    , "}"
    , ""
    , "function cancelSelection() {"
    , "  selectedDomino = null;"
    , "  document.getElementById('side-selector').classList.add('hidden');"
    , "  render();"
    , "}"
    , ""
    , "function goToMenu() {"
    , "  location.href = '/';"
    , "}"
    , ""
    , "function createDominoElement(domino, isBoard) {"
    , "  const div = document.createElement('div');"
    , "  const classes = ['domino'];"
    , "  "
    , "  if (isBoard) {"
    , "    classes.push('board-tile');"
    , "    classes.push(domino.isVertical ? 'vertical' : 'horizontal');"
    , "    // Aplicar posición absoluta"
    , "    div.style.left = domino.x + 'px';"
    , "    div.style.top = domino.y + 'px';"
    , "    // Aplicar rotación si existe"
    , "    if (domino.rotation && domino.rotation !== 0) {"
    , "      div.style.transform = 'rotate(' + domino.rotation + 'deg)';"
    , "      div.style.transformOrigin = 'center center';"
    , "    }"
    , "  } else {"
    , "    classes.push('vertical');"
    , "    if (selectedDomino && selectedDomino.left === domino.left && selectedDomino.right === domino.right) {"
    , "      classes.push('selected');"
    , "    }"
    , "  }"
    , "  "
    , "  div.className = classes.join(' ');"
    , "  "
    , "  const half1 = document.createElement('div');"
    , "  half1.className = 'domino-half';"
    , "  half1.innerHTML = renderPips(domino.left);"
    , "  "
    , "  const half2 = document.createElement('div');"
    , "  half2.className = 'domino-half';"
    , "  half2.innerHTML = renderPips(domino.right);"
    , "  "
    , "  div.appendChild(half1);"
    , "  div.appendChild(half2);"
    , "  "
    , "  if (!isBoard) {"
    , "    div.onclick = () => selectDomino(domino);"
    , "  }"
    , "  "
    , "  return div;"
    , "}"
    , ""
    , "function renderPips(n) {"
    , "  const positions = {"
    , "    0: [],"
    , "    1: [[50, 50]],"
    , "    2: [[25, 25], [75, 75]],"
    , "    3: [[25, 25], [50, 50], [75, 75]],"
    , "    4: [[25, 25], [75, 25], [25, 75], [75, 75]],"
    , "    5: [[25, 25], [75, 25], [50, 50], [25, 75], [75, 75]],"
    , "    6: [[25, 25], [25, 50], [25, 75], [75, 25], [75, 50], [75, 75]],"
    , "    7: [[25, 25], [25, 50], [25, 75], [50, 50], [75, 25], [75, 50], [75, 75]],"
    , "    8: [[25, 25], [25, 50], [25, 75], [50, 25], [50, 75], [75, 25], [75, 50], [75, 75]],"
    , "    9: [[25, 25], [25, 50], [25, 75], [50, 25], [50, 50], [50, 75], [75, 25], [75, 50], [75, 75]]"
    , "  };"
    , "  return (positions[n] || []).map(([x, y]) => "
    , "    `<span class='pip' style='left:${x}%;top:${y}%;transform:translate(-50%,-50%)'></span>`"
    , "  ).join('');"
    , "}"
    , ""
    , "function render() {"
    , "  if (!gameState) return;"
    , "  "
    , "  // Mensaje"
    , "  document.getElementById('message').textContent = gameState.grMessage;"
    , "  "
    , "  // Jugadores con equipos"
    , "  const playersDiv = document.getElementById('players');"
    , "  const is2vs2 = gameState.grVsMode === '2vs2';"
    , "  "
    , "  if (is2vs2) {"
    , "    // En modo 2vs2, mostrar jugadores agrupados por equipo"
    , "    const teamA = gameState.grPlayers.filter(p => p.pjTeam === 'A');"
    , "    const teamB = gameState.grPlayers.filter(p => p.pjTeam === 'B');"
    , "    playersDiv.innerHTML = `"
    , "      <div class='team-container team-a'>"
    , "        <div class='team-label'>🟢 Tu Equipo</div>"
    , "        ${teamA.map((p, i) => `"
    , "          <div class='player-card ${gameState.grPlayers.indexOf(p) === gameState.grCurrentPlayer ? 'active' : ''} team-a-player'>"
    , "            <div class='name'>${p.pjName}</div>"
    , "            <div class='count'>${p.pjHandCount} fichas</div>"
    , "          </div>`).join('')}"
    , "      </div>"
    , "      <div class='team-container team-b'>"
    , "        <div class='team-label'>🔴 Equipo Rival</div>"
    , "        ${teamB.map((p, i) => `"
    , "          <div class='player-card ${gameState.grPlayers.indexOf(p) === gameState.grCurrentPlayer ? 'active' : ''} team-b-player'>"
    , "            <div class='name'>${p.pjName}</div>"
    , "            <div class='count'>${p.pjHandCount} fichas</div>"
    , "          </div>`).join('')}"
    , "      </div>"
    , "    `;"
    , "    playersDiv.innerHTML += `<div class='player-card'><div class='name'>Pozo</div><div class='count'>${gameState.grPozoCount} fichas</div></div>`;"
    , "  } else {"
    , "    playersDiv.innerHTML = gameState.grPlayers.map((p, i) => `"
    , "      <div class='player-card ${i === gameState.grCurrentPlayer ? 'active' : ''}'>"
    , "        <div class='name'>${p.pjName}</div>"
    , "        <div class='count'>${p.pjHandCount} fichas</div>"
    , "      </div>"
    , "    `).join('');"
    , "    playersDiv.innerHTML += `<div class='player-card'><div class='name'>Pozo</div><div class='count'>${gameState.grPozoCount} fichas</div></div>`;"
    , "  }"
    , "  "
    , "  // Tablero"
    , "  const boardDiv = document.getElementById('board');"
    , "  boardDiv.innerHTML = '';"
    , "  "
    , "  // Calcular offset para centrar las fichas (el servidor usa 550 como centro X)"
    , "  const boardRect = boardDiv.getBoundingClientRect();"
    , "  const offsetX = (boardRect.width / 2) - 550;"
    , "  const offsetY = (boardRect.height / 2) - 350;"
    , "  "
    , "  if (gameState.grBoard.bjTiles.length === 0) {"
    , "    const emptyMsg = document.createElement('p');"
    , "    emptyMsg.style.color = '#90EE90';"
    , "    emptyMsg.style.position = 'absolute';"
    , "    emptyMsg.style.left = '50%';"
    , "    emptyMsg.style.top = '50%';"
    , "    emptyMsg.style.transform = 'translate(-50%, -50%)';"
    , "    emptyMsg.textContent = 'Mesa vacía - Juega la primera ficha';"
    , "    boardDiv.appendChild(emptyMsg);"
    , "  } else {"
    , "    gameState.grBoard.bjTiles.forEach(tile => {"
    , "      const elem = createDominoElement(tile, true);"
    , "      // Aplicar offset para centrar"
    , "      elem.style.left = (tile.x + offsetX) + 'px';"
    , "      elem.style.top = (tile.y + offsetY) + 'px';"
    , "      boardDiv.appendChild(elem);"
    , "    });"
    , "  }"
    , "  "
    , "  // Mano del jugador (según control seleccionado)"
    , "  const handDiv = document.getElementById('hand');"
    , "  handDiv.innerHTML = '';"
    , "  const handIndex = (controlled === 'all') ? gameState.grCurrentPlayer : parseInt(controlled);"
    , "  const myHand = gameState.grPlayers[handIndex].pjHand;"
    , "  console.log('Renderizando mano:', myHand);"
    , "  console.log('Índice de mano:', handIndex);"
    , "  document.getElementById('hand-count').textContent = `(${myHand.length} fichas)`;"
    , "  myHand.forEach(tile => {"
    , "    console.log('Creando ficha:', tile);"
    , "    handDiv.appendChild(createDominoElement(tile, false));"
    , "  });"
    , "  "
    , "  // Botones (habilitados solo si es el turno del jugador controlado)"
    , "  const canPlay = (controlled === 'all' ? true : (parseInt(controlled) === gameState.grCurrentPlayer)) && !gameState.grGameOver;"
    , "  document.getElementById('btn-draw').disabled = !gameState.grCanDraw || !canPlay;"
    , "  document.getElementById('btn-pass').disabled = !canPlay;"
    , "  "
    , "  // Game over"
    , "  if (gameState.grGameOver) {"
    , "    const ms = gameState.grMatchState;"
    , "    const isDataA100 = ms !== null && ms !== undefined;"
    , "    const matchOver = isDataA100 && ms.msjMatchOver;"
    , "    "
    , "    // Actualizar título del modal"
    , "    const modalTitle = document.querySelector('#game-over-modal h2');"
    , "    if (matchOver) {"
    , "      modalTitle.textContent = '🏆 ¡Partida Terminada!';"
    , "    } else if (isDataA100) {"
    , "      modalTitle.textContent = '🎯 ¡Ronda Terminada!';"
    , "    } else {"
    , "      modalTitle.textContent = '🎉 ¡Juego Terminado!';"
    , "    }"
    , "    "
    , "    // Texto del ganador"
    , "    const winDetailsDiv = document.getElementById('win-details');"
    , "    if (gameState.grWinDetails) {"
    , "      winDetailsDiv.innerHTML = gameState.grWinDetails.replace(/\\\\n/g, '<br>');"
    , "      winDetailsDiv.classList.remove('hidden');"
    , "    } else {"
    , "      winDetailsDiv.classList.add('hidden');"
    , "    }"
    , "    "
    , "    document.getElementById('winner-text').textContent = gameState.grWinner ? "
    , "      `🏆 Ganador: ${gameState.grWinner}` : '🤝 Empate';"
    , "    "
    , "    // Mostrar resumen de puntuación si es Data a 100"
    , "    const summaryDiv = document.getElementById('match-score-summary');"
    , "    const btnNextRound = document.getElementById('btn-next-round-modal');"
    , "    const btnNewGame = document.getElementById('btn-new-game-modal');"
    , "    "
    , "    if (isDataA100) {"
    , "      summaryDiv.classList.remove('hidden');"
    , "      summaryDiv.innerHTML = `"
    , "        <div class='scores'>"
    , "          <span class='team-a'>Tu Equipo: <strong>${ms.msjTeamAScore}</strong></span>"
    , "          <span class='team-b'>Rivales: <strong>${ms.msjTeamBScore}</strong></span>"
    , "        </div>"
    , "        <div class='target'>Primero en llegar a ${ms.msjTargetScore} pierde</div>"
    , "        ${matchOver ? `<div class='match-winner-text'>${ms.msjMatchWinner === 'A' ? '¡TU EQUIPO GANA LA DATA!' : '¡EQUIPO RIVAL GANA LA DATA!'}</div>` : ''}"
    , "      `;"
    , "      "
    , "      // Mostrar botón de siguiente ronda solo si la partida no terminó"
    , "      if (matchOver) {"
    , "        btnNextRound.classList.add('hidden');"
    , "        btnNewGame.textContent = '🔄 Nueva Data a 100';"
    , "      } else {"
    , "        btnNextRound.classList.remove('hidden');"
    , "        btnNewGame.textContent = '🔄 Nueva Partida';"
    , "      }"
    , "    } else {"
    , "      summaryDiv.classList.add('hidden');"
    , "      btnNextRound.classList.add('hidden');"
    , "      btnNewGame.textContent = '🔄 Nueva Partida';"
    , "    }"
    , "    "
    , "    document.getElementById('game-over-modal').classList.remove('hidden');"
    , "  }"
    , "  "
    , "  // Panel de Data a 100"
    , "  renderMatchScorePanel();"
    , "}"
    , ""
    , "function renderMatchScorePanel() {"
    , "  let panel = document.getElementById('match-score-panel');"
    , "  const ms = gameState.grMatchState;"
    , "  "
    , "  if (!ms) {"
    , "    if (panel) panel.remove();"
    , "    return;"
    , "  }"
    , "  "
    , "  if (!panel) {"
    , "    panel = document.createElement('div');"
    , "    panel.id = 'match-score-panel';"
    , "    panel.className = 'match-score-panel';"
    , "    document.body.appendChild(panel);"
    , "  }"
    , "  "
    , "  const bonusInfo = [];"
    , "  if (ms.msjBonusNoSalida) bonusInfo.push('🚫 No salida +20');"
    , "  if (ms.msjBonusPrimerDoble && ms.msjIsFirstRound) bonusInfo.push('🥇 1er partido x2');"
    , "  if (ms.msjBonusCapicua) bonusInfo.push('🔄 Capicúa x2');"
    , "  "
    , "  let html = `"
    , "    <h3>🎯 Data a ${ms.msjTargetScore}</h3>"
    , "    <div class='match-round'>Ronda ${ms.msjRoundNumber}</div>"
    , "    <div class='match-scores'>"
    , "      <div class='team-score team-a'>"
    , "        <div class='label'>Tu Equipo</div>"
    , "        <div class='score'>${ms.msjTeamAScore}</div>"
    , "      </div>"
    , "      <div class='team-score team-b'>"
    , "        <div class='label'>Rivales</div>"
    , "        <div class='score'>${ms.msjTeamBScore}</div>"
    , "      </div>"
    , "    </div>"
    , "    <div class='match-target'>Primer equipo en llegar a ${ms.msjTargetScore} pierde</div>"
    , "  `;"
    , "  "
    , "  if (bonusInfo.length > 0) {"
    , "    html += `<div class='match-bonuses' style='font-size:0.7rem;margin-top:0.5rem;opacity:0.7'>${bonusInfo.join(' | ')}</div>`;"
    , "  }"
    , "  "
    , "  if (ms.msjMatchOver) {"
    , "    const winner = ms.msjMatchWinner === 'A' ? '¡Tu Equipo Gana!' : '¡Equipo Rival Gana!';"
    , "    html += `<div class='match-winner' style='color:#FFC107;font-weight:bold;margin-top:0.5rem'>${winner}</div>`;"
    , "  } else if (gameState.grGameOver) {"
    , "    html += `<button class='btn-next-round' onclick='nextRound()'>▶️ Siguiente Ronda</button>`;"
    , "  }"
    , "  "
    , "  panel.innerHTML = html;"
    , "}"
    , ""
    , "async function nextRound() {"
    , "  const res = await fetch('/api/next-round', { method: 'POST' });"
    , "  gameState = await res.json();"
    , "  selectedDomino = null;"
    , "  document.getElementById('game-over-modal').classList.add('hidden');"
    , "  render();"
    , "}"
    , ""
    , "// Auto-play para bots (jugadores 1, 2, 3)"
    , "let botPlaying = false;"
    , "async function botTurn() {"
    , "  if (botPlaying) return;"
    , "  if (controlled !== '0') return;"
    , "  if (!gameState || gameState.grGameOver || gameState.grCurrentPlayer === 0) return;"
    , "  "
    , "  botPlaying = true;"
    , "  const currentBot = gameState.grPlayers[gameState.grCurrentPlayer];"
    , "  const botName = currentBot ? currentBot.pjName : 'Bot';"
    , "  "
    , "  // Mostrar mensaje de que el bot está pensando"
    , "  document.getElementById('message').textContent = `🤔 ${botName} está pensando...`;"
    , "  "
    , "  // Esperar 2 segundos para que el jugador vea"
    , "  await new Promise(r => setTimeout(r, 2000));"
    , "  "
    , "  // Ejecutar la jugada del bot"
    , "  await fetch('/api/bot-play', { method: 'POST' });"
    , "  await fetchState();"
    , "  "
    , "  botPlaying = false;"
    , "}"
    , ""
    , "setInterval(botTurn, 500);"
    , ""
    , "// Iniciar"
    , "newGame();"
    ]
