{-# LANGUAGE OverloadedStrings #-}

module Web.Views 
    ( indexHtml
    , gameHtml
    ) where

import Data.Text.Lazy (Text)
import qualified Data.Text.Lazy as TL

-- | Página principal
indexHtml :: Text
indexHtml = TL.concat
    [ "<!DOCTYPE html>"
    , "<html lang='es'>"
    , "<head>"
    , "  <meta charset='UTF-8'>"
    , "  <meta name='viewport' content='width=device-width, initial-scale=1.0'>"
    , "  <title>Dominó - Haskell</title>"
    , "  <style>", cssStyles, indexCssStyles, "</style>"
    , "</head>"
    , "<body>"
    , "  <div class='container'>"
    , "    <h1>🎲 Dominó</h1>"
    , "    <p>Juego de dominó implementado en Haskell</p>"
    , "    <div class='difficulty-selector'>"
    , "      <h2>Selecciona la dificultad:</h2>"
    , "      <div class='difficulty-buttons'>"
    , "        <button onclick=\"startGame('facil')\" class='btn-difficulty btn-easy'>😊 Fácil</button>"
    , "        <button onclick=\"startGame('medio')\" class='btn-difficulty btn-medium'>🤔 Medio</button>"
    , "        <button onclick=\"startGame('dificil')\" class='btn-difficulty btn-hard'>😈 Difícil</button>"
    , "      </div>"
    , "    </div>"
    , "  </div>"
    , "  <script>"
    , "    function startGame(difficulty) {"
    , "      localStorage.setItem('domino-difficulty', difficulty);"
    , "      location.href = '/game';"
    , "    }"
    , "  </script>"
    , "</body>"
    , "</html>"
    ]

-- | Página del juego
gameHtml :: Text
gameHtml = TL.concat
    [ "<!DOCTYPE html>"
    , "<html lang='es'>"
    , "<head>"
    , "  <meta charset='UTF-8'>"
    , "  <meta name='viewport' content='width=device-width, initial-scale=1.0'>"
    , "  <title>Dominó - Partida</title>"
    , "  <style>", cssStyles, "</style>"
    , "</head>"
    , "<body>"
    , "  <div class='game-container'>"
    , "    <header>"
    , "      <h1>🎲 Dominó</h1>"
    , "      <div id='message' class='message'></div>"
    , "    </header>"
    , "    "
    , "    <div class='players-info'>"
    , "      <div id='players'></div>"
    , "      <div style='margin-left:1rem;'>Controlar: <select id='control-select' onchange='onControlChange(this.value)'>"
    , "        <option value=\"0\">Jugador 0 (Tú)</option>"
    , "        <option value=\"1\">Jugador 1</option>"
    , "        <option value=\"2\">Jugador 2</option>"
    , "        <option value=\"3\">Jugador 3</option>"
    , "        <option value=\"all\">Todos (control manual de todos)</option>"
    , "      </select></div>"
    , "    </div>"
    , "    "
    , "    <div class='board-container'>"
    , "      <h3>Mesa</h3>"
    , "      <div id='board' class='board'></div>"
    , "    </div>"
    , "    "
    , "    <div class='hand-container'>"
    , "      <h3>Tu mano <span id='hand-count'></span></h3>"
    , "      <div id='hand' class='hand'></div>"
    , "    </div>"
    , "    "
    , "    <div class='actions'>"
    , "      <button id='btn-draw' class='btn' onclick='drawTile()'>🎴 Robar</button>"
    , "      <button id='btn-pass' class='btn' onclick='passTurn()'>⏭️ Pasar</button>"
    , "      <button class='btn btn-new' onclick='newGame()'>🔄 Nueva Partida</button>"
    , "    </div>"
    , "    "
    , "    <div id='side-selector' class='side-selector hidden'>"
    , "      <p>¿En qué lado quieres jugar?</p>"
    , "      <button class='btn' onclick='playSelected(\"left\")'>⬅️ Izquierda</button>"
    , "      <button class='btn' onclick='playSelected(\"right\")'>➡️ Derecha</button>"
    , "      <button class='btn btn-cancel' onclick='cancelSelection()'>Cancelar</button>"
    , "    </div>"
    , "  </div>"
    , "  "
    , "  <div id='game-over-modal' class='modal hidden'>"
    , "    <div class='modal-content'>"
    , "      <h2>🎉 ¡Juego Terminado!</h2>"
    , "      <p id='winner-text'></p>"
    , "      <button class='btn btn-new' onclick='newGame()'>Nueva Partida</button>"
    , "    </div>"
    , "  </div>"
    , "  "
    , "  <script>", jsScript, "</script>"
    , "</body>"
    , "</html>"
    ]

-- | Estilos CSS
cssStyles :: Text
cssStyles = TL.concat
    [ "* { box-sizing: border-box; margin: 0; padding: 0; }"
    , "body { "
    , "  font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;"
    , "  background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);"
    , "  min-height: 100vh;"
    , "  color: #fff;"
    , "}"
    , ".container {"
    , "  display: flex;"
    , "  flex-direction: column;"
    , "  align-items: center;"
    , "  justify-content: center;"
    , "  min-height: 100vh;"
    , "  text-align: center;"
    , "}"
    , ".container h1 { font-size: 4rem; margin-bottom: 1rem; }"
    , ".container p { font-size: 1.2rem; margin-bottom: 2rem; color: #aaa; }"
    , ".btn-start {"
    , "  padding: 1rem 3rem;"
    , "  font-size: 1.5rem;"
    , "  background: linear-gradient(45deg, #e94560, #ff6b6b);"
    , "  border: none;"
    , "  border-radius: 50px;"
    , "  color: white;"
    , "  cursor: pointer;"
    , "  transition: transform 0.3s, box-shadow 0.3s;"
    , "}"
    , ".btn-start:hover {"
    , "  transform: scale(1.05);"
    , "  box-shadow: 0 10px 30px rgba(233, 69, 96, 0.4);"
    , "}"
    , ".game-container {"
    , "  max-width: 1200px;"
    , "  margin: 0 auto;"
    , "  padding: 1rem;"
    , "}"
    , "header {"
    , "  text-align: center;"
    , "  padding: 1rem;"
    , "}"
    , "header h1 { font-size: 2rem; }"
    , ".message {"
    , "  background: rgba(255,255,255,0.1);"
    , "  padding: 0.5rem 1rem;"
    , "  border-radius: 10px;"
    , "  margin-top: 0.5rem;"
    , "  font-size: 1.1rem;"
    , "}"
    , ".players-info {"
    , "  display: flex;"
    , "  justify-content: center;"
    , "  gap: 1rem;"
    , "  flex-wrap: wrap;"
    , "  margin: 1rem 0;"
    , "}"
    , ".player-card {"
    , "  background: rgba(255,255,255,0.1);"
    , "  padding: 0.5rem 1rem;"
    , "  border-radius: 10px;"
    , "  min-width: 120px;"
    , "}"
    , ".player-card.active {"
    , "  background: linear-gradient(45deg, #e94560, #ff6b6b);"
    , "  box-shadow: 0 5px 20px rgba(233, 69, 96, 0.4);"
    , "}"
    , ".player-card .name { font-weight: bold; }"
    , ".player-card .count { font-size: 0.9rem; opacity: 0.8; }"
    , ".board-container {"
    , "  background: #2d5016;"
    , "  border-radius: 20px;"
    , "  padding: 1rem;"
    , "  margin: 1rem 0;"
    , "  min-height: 200px;"
    , "  box-shadow: inset 0 5px 20px rgba(0,0,0,0.3);"
    , "}"
    , ".board-container h3 {"
    , "  text-align: center;"
    , "  margin-bottom: 1rem;"
    , "  color: #90EE90;"
    , "}"
    , ".board {"
    , "  display: flex;"
    , "  flex-wrap: wrap;"
    , "  justify-content: center;"
    , "  align-items: center;"
    , "  gap: 4px;"
    , "  min-height: 100px;"
    , "  padding: 1rem;"
    , "}"
    , ".hand-container {"
    , "  background: rgba(255,255,255,0.05);"
    , "  border-radius: 20px;"
    , "  padding: 1rem;"
    , "  margin: 1rem 0;"
    , "}"
    , ".hand-container h3 {"
    , "  text-align: center;"
    , "  margin-bottom: 1rem;"
    , "}"
    , ".hand {"
    , "  display: flex;"
    , "  flex-wrap: wrap;"
    , "  justify-content: center;"
    , "  gap: 8px;"
    , "}"
    , ".domino {"
    , "  background: linear-gradient(145deg, #fff, #e0e0e0);"
    , "  border-radius: 8px;"
    , "  display: flex;"
    , "  box-shadow: 2px 2px 8px rgba(0,0,0,0.3);"
    , "  cursor: pointer;"
    , "  transition: transform 0.2s, box-shadow 0.2s;"
    , "}"
    , ".domino:hover {"
    , "  transform: translateY(-5px);"
    , "  box-shadow: 4px 8px 16px rgba(0,0,0,0.4);"
    , "}"
    , ".domino.selected {"
    , "  box-shadow: 0 0 20px #00ff00;"
    , "  transform: translateY(-10px);"
    , "}"
    , ".domino.horizontal {"
    , "  flex-direction: row;"
    , "  width: 70px;"
    , "  height: 35px;"
    , "}"
    , ".domino.vertical {"
    , "  flex-direction: column;"
    , "  width: 35px;"
    , "  height: 70px;"
    , "}"
    , ".domino-half {"
    , "  flex: 1;"
    , "  display: flex;"
    , "  justify-content: center;"
    , "  align-items: center;"
    , "  font-weight: bold;"
    , "  color: #333;"
    , "  font-size: 14px;"
    , "  position: relative;"
    , "}"
    , ".domino.horizontal .domino-half {"
    , "  border-right: 2px solid #999;"
    , "}"
    , ".domino.horizontal .domino-half:last-child {"
    , "  border-right: none;"
    , "}"
    , ".domino.vertical .domino-half {"
    , "  border-bottom: 2px solid #999;"
    , "}"
    , ".domino.vertical .domino-half:last-child {"
    , "  border-bottom: none;"
    , "}"
    , ".domino.board-tile {"
    , "  cursor: default;"
    , "  transform: none;"
    , "}"
    , ".domino.board-tile:hover {"
    , "  transform: none;"
    , "}"
    , ".domino.double {"
    , "  flex-direction: column;"
    , "  width: 35px;"
    , "  height: 70px;"
    , "}"
    , ".actions {"
    , "  display: flex;"
    , "  justify-content: center;"
    , "  gap: 1rem;"
    , "  margin: 1rem 0;"
    , "  flex-wrap: wrap;"
    , "}"
    , ".btn {"
    , "  padding: 0.8rem 1.5rem;"
    , "  font-size: 1rem;"
    , "  background: rgba(255,255,255,0.1);"
    , "  border: 1px solid rgba(255,255,255,0.2);"
    , "  border-radius: 10px;"
    , "  color: white;"
    , "  cursor: pointer;"
    , "  transition: all 0.3s;"
    , "}"
    , ".btn:hover {"
    , "  background: rgba(255,255,255,0.2);"
    , "}"
    , ".btn:disabled {"
    , "  opacity: 0.5;"
    , "  cursor: not-allowed;"
    , "}"
    , ".btn-new {"
    , "  background: linear-gradient(45deg, #e94560, #ff6b6b);"
    , "  border: none;"
    , "}"
    , ".btn-cancel {"
    , "  background: rgba(255,0,0,0.3);"
    , "}"
    , ".side-selector {"
    , "  position: fixed;"
    , "  bottom: 20px;"
    , "  left: 50%;"
    , "  transform: translateX(-50%);"
    , "  background: rgba(0,0,0,0.9);"
    , "  padding: 1rem 2rem;"
    , "  border-radius: 15px;"
    , "  text-align: center;"
    , "  z-index: 100;"
    , "  box-shadow: 0 10px 40px rgba(0,0,0,0.5);"
    , "}"
    , ".side-selector p { margin-bottom: 1rem; }"
    , ".hidden { display: none !important; }"
    , ".modal {"
    , "  position: fixed;"
    , "  top: 0;"
    , "  left: 0;"
    , "  width: 100%;"
    , "  height: 100%;"
    , "  background: rgba(0,0,0,0.8);"
    , "  display: flex;"
    , "  justify-content: center;"
    , "  align-items: center;"
    , "  z-index: 1000;"
    , "}"
    , ".modal-content {"
    , "  background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);"
    , "  padding: 3rem;"
    , "  border-radius: 20px;"
    , "  text-align: center;"
    , "  box-shadow: 0 20px 60px rgba(0,0,0,0.5);"
    , "}"
    , ".modal-content h2 { font-size: 2rem; margin-bottom: 1rem; }"
    , ".modal-content p { margin-bottom: 2rem; font-size: 1.2rem; }"
    , ".pip {"
    , "  width: 6px;"
    , "  height: 6px;"
    , "  background: #333;"
    , "  border-radius: 50%;"
    , "  position: absolute;"
    , "}"
    ]

-- | Estilos adicionales para la página de inicio
indexCssStyles :: Text
indexCssStyles = TL.concat
    [ ".difficulty-selector {"
    , "  margin-top: 3rem;"
    , "  display: flex;"
    , "  flex-direction: column;"
    , "  align-items: center;"
    , "  gap: 2rem;"
    , "}"
    , ".difficulty-selector h2 {"
    , "  font-size: 1.8rem;"
    , "  margin-bottom: 0;"
    , "}"
    , ".difficulty-buttons {"
    , "  display: flex;"
    , "  gap: 2rem;"
    , "  flex-wrap: wrap;"
    , "  justify-content: center;"
    , "}"
    , ".btn-difficulty {"
    , "  padding: 1.5rem 3rem;"
    , "  font-size: 1.5rem;"
    , "  border: none;"
    , "  border-radius: 15px;"
    , "  color: white;"
    , "  cursor: pointer;"
    , "  transition: transform 0.3s, box-shadow 0.3s;"
    , "  font-weight: bold;"
    , "  min-width: 200px;"
    , "}"
    , ".btn-easy {"
    , "  background: linear-gradient(45deg, #4CAF50, #8BC34A);"
    , "}"
    , ".btn-easy:hover {"
    , "  transform: scale(1.05);"
    , "  box-shadow: 0 10px 30px rgba(76, 175, 80, 0.5);"
    , "}"
    , ".btn-medium {"
    , "  background: linear-gradient(45deg, #FF9800, #FFC107);"
    , "}"
    , ".btn-medium:hover {"
    , "  transform: scale(1.05);"
    , "  box-shadow: 0 10px 30px rgba(255, 152, 0, 0.5);"
    , "}"
    , ".btn-hard {"
    , "  background: linear-gradient(45deg, #f44336, #E91E63);"
    , "}"
    , ".btn-hard:hover {"
    , "  transform: scale(1.05);"
    , "  box-shadow: 0 10px 30px rgba(244, 67, 54, 0.5);"
    , "}"
    ]

-- | JavaScript del juego
jsScript :: Text
jsScript = TL.unlines
    [ "let gameState = null;"
    , "let selectedDomino = null;"
    , "let controlled = '0'; // '0','1','2','3' or 'all'"
    , "function onControlChange(v) { controlled = v; render(); }"
    , ""
    , "async function fetchState() {"
    , "  const res = await fetch('/api/state');"
    , "  gameState = await res.json();"
    , "  console.log('Estado recibido:', gameState);"
    , "  console.log('Mano jugador 0:', gameState.grPlayers[0].pjHand);"
    , "  render();"
    , "}"
    , ""
    , "async function newGame() {"
    , "  const difficulty = localStorage.getItem('domino-difficulty') || 'facil';"
    , "  const res = await fetch('/api/new', { "
    , "    method: 'POST',"
    , "    headers: { 'Content-Type': 'application/json' },"
    , "    body: JSON.stringify({ difficulty: difficulty })"
    , "  });"
    , "  gameState = await res.json();"
    , "  selectedDomino = null;"
    , "  document.getElementById('game-over-modal').classList.add('hidden');"
    , "  render();"
    , "}"
    , ""
    , "async function playTile(domino, side) {"
    , "  const res = await fetch('/api/play', {"
    , "    method: 'POST',"
    , "    headers: { 'Content-Type': 'application/json' },"
    , "    body: JSON.stringify({ action: 'play', domino: domino, side: side })"
    , "  });"
    , "  gameState = await res.json();"
    , "  selectedDomino = null;"
    , "  render();"
    , "}"
    , ""
    , "async function drawTile() {"
    , "  const res = await fetch('/api/play', {"
    , "    method: 'POST',"
    , "    headers: { 'Content-Type': 'application/json' },"
    , "    body: JSON.stringify({ action: 'draw', domino: null, side: null })"
    , "  });"
    , "  gameState = await res.json();"
    , "  render();"
    , "}"
    , ""
    , "async function passTurn() {"
    , "  const res = await fetch('/api/play', {"
    , "    method: 'POST',"
    , "    headers: { 'Content-Type': 'application/json' },"
    , "    body: JSON.stringify({ action: 'pass', domino: null, side: null })"
    , "  });"
    , "  gameState = await res.json();"
    , "  render();"
    , "}"
    , ""
    , "function isControlledTurn() { return controlled === 'all' || (parseInt(controlled) === gameState.grCurrentPlayer); }"
    , "function selectDomino(domino) {"
    , "  if (gameState.grGameOver) return;"
    , "  if (!isControlledTurn()) {"
    , "    alert('No es tu turno (control seleccionado). Cambia el control para jugar este jugador.');"
    , "    return;"
    , "  }"
    , "  selectedDomino = domino;"
    , "  "
    , "  // Si el tablero está vacío, jugar automáticamente"
    , "  if (gameState.grBoard.bjTiles.length === 0) {"
    , "    playTile(domino, 'right');"
    , "    return;"
    , "  }"
    , "  "
    , "  // Mostrar selector de lado"
    , "  document.getElementById('side-selector').classList.remove('hidden');"
    , "  render();"
    , "}"
    , ""
    , "function playSelected(side) {"
    , "  if (selectedDomino) {"
    , "    playTile(selectedDomino, side);"
    , "  }"
    , "  document.getElementById('side-selector').classList.add('hidden');"
    , "}"
    , ""
    , "function cancelSelection() {"
    , "  selectedDomino = null;"
    , "  document.getElementById('side-selector').classList.add('hidden');"
    , "  render();"
    , "}"
    , ""
    , "function createDominoElement(domino, isDouble, isBoard) {"
    , "  const div = document.createElement('div');"
    , "  const classes = ['domino'];"
    , "  "
    , "  if (isBoard) {"
    , "    classes.push('board-tile');"
    , "    classes.push(isDouble ? 'vertical' : 'horizontal');"
    , "  } else {"
    , "    classes.push('vertical');"
    , "    if (selectedDomino && selectedDomino.left === domino.left && selectedDomino.right === domino.right) {"
    , "      classes.push('selected');"
    , "    }"
    , "  }"
    , "  "
    , "  div.className = classes.join(' ');"
    , "  "
    , "  const half1 = document.createElement('div');"
    , "  half1.className = 'domino-half';"
    , "  half1.innerHTML = renderPips(domino.left);"
    , "  "
    , "  const half2 = document.createElement('div');"
    , "  half2.className = 'domino-half';"
    , "  half2.innerHTML = renderPips(domino.right);"
    , "  "
    , "  div.appendChild(half1);"
    , "  div.appendChild(half2);"
    , "  "
    , "  if (!isBoard) {"
    , "    div.onclick = () => selectDomino(domino);"
    , "  }"
    , "  "
    , "  return div;"
    , "}"
    , ""
    , "function renderPips(n) {"
    , "  const positions = {"
    , "    0: [],"
    , "    1: [[50, 50]],"
    , "    2: [[25, 25], [75, 75]],"
    , "    3: [[25, 25], [50, 50], [75, 75]],"
    , "    4: [[25, 25], [75, 25], [25, 75], [75, 75]],"
    , "    5: [[25, 25], [75, 25], [50, 50], [25, 75], [75, 75]],"
    , "    6: [[25, 25], [25, 50], [25, 75], [75, 25], [75, 50], [75, 75]],"
    , "    7: [[25, 25], [25, 50], [25, 75], [50, 50], [75, 25], [75, 50], [75, 75]],"
    , "    8: [[25, 25], [25, 50], [25, 75], [50, 25], [50, 75], [75, 25], [75, 50], [75, 75]],"
    , "    9: [[25, 25], [25, 50], [25, 75], [50, 25], [50, 50], [50, 75], [75, 25], [75, 50], [75, 75]]"
    , "  };"
    , "  return (positions[n] || []).map(([x, y]) => "
    , "    `<span class='pip' style='left:${x}%;top:${y}%;transform:translate(-50%,-50%)'></span>`"
    , "  ).join('');"
    , "}"
    , ""
    , "function render() {"
    , "  if (!gameState) return;"
    , "  "
    , "  // Mensaje"
    , "  document.getElementById('message').textContent = gameState.grMessage;"
    , "  "
    , "  // Jugadores"
    , "  const playersDiv = document.getElementById('players');"
    , "  playersDiv.innerHTML = gameState.grPlayers.map((p, i) => `"
    , "    <div class='player-card ${i === gameState.grCurrentPlayer ? 'active' : ''}'>"
    , "      <div class='name'>${p.pjName}</div>"
    , "      <div class='count'>${p.pjHandCount} fichas</div>"
    , "    </div>"
    , "  `).join('');"
    , "  playersDiv.innerHTML += `<div class='player-card'><div class='name'>Pozo</div><div class='count'>${gameState.grPozoCount} fichas</div></div>`;"
    , "  "
    , "  // Tablero"
    , "  const boardDiv = document.getElementById('board');"
    , "  boardDiv.innerHTML = '';"
    , "  if (gameState.grBoard.bjTiles.length === 0) {"
    , "    boardDiv.innerHTML = '<p style=\"color: #90EE90;\">Mesa vacía - Juega la primera ficha</p>';"
    , "  } else {"
    , "    gameState.grBoard.bjTiles.forEach(tile => {"
    , "      const isDouble = tile.left === tile.right;"
    , "      boardDiv.appendChild(createDominoElement(tile, isDouble, true));"
    , "    });"
    , "  }"
    , "  "
    , "  // Mano del jugador (según control seleccionado)"
    , "  const handDiv = document.getElementById('hand');"
    , "  handDiv.innerHTML = '';"
    , "  const handIndex = (controlled === 'all') ? gameState.grCurrentPlayer : parseInt(controlled);"
    , "  const myHand = gameState.grPlayers[handIndex].pjHand;"
    , "  console.log('Renderizando mano:', myHand);"
    , "  console.log('Índice de mano:', handIndex);"
    , "  document.getElementById('hand-count').textContent = `(${myHand.length} fichas)`;"
    , "  myHand.forEach(tile => {"
    , "    console.log('Creando ficha:', tile);"
    , "    handDiv.appendChild(createDominoElement(tile, false, false));"
    , "  });"
    , "  "
    , "  // Botones (habilitados solo si es el turno del jugador controlado)"
    , "  const canPlay = (controlled === 'all' ? true : (parseInt(controlled) === gameState.grCurrentPlayer)) && !gameState.grGameOver;"
    , "  document.getElementById('btn-draw').disabled = !gameState.grCanDraw || !canPlay;"
    , "  document.getElementById('btn-pass').disabled = !canPlay;"
    , "  "
    , "  // Game over"
    , "  if (gameState.grGameOver) {"
    , "    document.getElementById('winner-text').textContent = gameState.grWinner ? "
    , "      `Ganador: ${gameState.grWinner}` : 'Empate';"
    , "    document.getElementById('game-over-modal').classList.remove('hidden');"
    , "  }"
    , "}"
    , ""
    , "// Auto-play para bots (jugadores 1, 2, 3)"
    , "setInterval(async () => {"
    , "  // Solo ejecutar autoplay cuando control está en '0' (modo normal)"
    , "  if (controlled !== '0') return;"
    , "  if (gameState && !gameState.grGameOver && gameState.grCurrentPlayer !== 0) {"
    , "    await fetch('/api/bot-play', { method: 'POST' });"
    , "    await fetchState();"
    , "  }"
    , "}, 1500);"
    , ""
    , "// Iniciar"
    , "fetchState();"
    ]
